Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2020-02, with the labels that each got.

#14 fix code coverage and docker config issue.
  CONTRIBUTING.md
  Makefile
  common/scripts/codecov.sh
  common/scripts/config_docker.sh
Labels: approved, lgtm, size/M

#21 e2e test
  Makefile
  go.mod
  go.sum
  test/config/constants.go
  test/e2e/commonserviceset_test.go
  test/e2e/main_test.go
  test/helpers/helpers.go
  test/testgroups/commonservice.go
  test/testsuits/commonserviceset.go
Labels: approved, lgtm, size/XXL

#22 Re-org Makefile
  Dockerfile
  Makefile
Labels: approved, lgtm, size/L

#23 Create doc for e2e test
  Makefile
  README.md
  docs/development.md
  docs/e2e.md
Labels: approved, lgtm, size/M

#26 Update CRD name
  Makefile
  deploy/crds/operator.ibm.com_metaoperatorcatalogs_crd.yaml
  deploy/crds/operator.ibm.com_metaoperatorconfigs_crd.yaml
  deploy/crds/operator.ibm.com_metaoperatorsets_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorcatalog_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorconfig_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorset_cr.yaml
  deploy/olm-catalog/common-service-operator/0.0.3/common-service-operator.v0.0.3.clusterserviceversion.yaml
  deploy/olm-catalog/common-service-operator/0.0.3/operator.ibm.com_metaoperatorcatalogs_crd.yaml
  deploy/olm-catalog/common-service-operator/0.0.3/operator.ibm.com_metaoperatorconfigs_crd.yaml
  deploy/olm-catalog/common-service-operator/0.0.3/operator.ibm.com_metaoperatorsets_crd.yaml
  deploy/role.yaml
  go.mod
  go.sum
  pkg/apis/operator/v1alpha1/metaoperatorcatalog_types.go
  pkg/apis/operator/v1alpha1/metaoperatorconfig_types.go
  pkg/apis/operator/v1alpha1/metaoperatorset_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/operator/v1alpha1/zz_generated.openapi.go
  pkg/controller/add_metaoperatorcatalog.go
  pkg/controller/add_metaoperatorconfig.go
  pkg/controller/add_metaoperatorset.go
  pkg/controller/metaoperatorcatalog/metaoperatorcatalog_controller.go
  pkg/controller/metaoperatorconfig/metaoperatorconfig_controller.go
  pkg/controller/metaoperatorset/catalog_status.go
  pkg/controller/metaoperatorset/config_status.go
  pkg/controller/metaoperatorset/metaoperatorset_controller.go
  pkg/controller/metaoperatorset/reconcile_commonserviceconfig.go
  pkg/controller/metaoperatorset/reconcile_metaoperatpor.go
  pkg/controller/metaoperatorset/set_status.go
  test/e2e/commonserviceset_test.go
  test/helpers/helpers.go
Labels: approved, lgtm, size/XXL

#28 Update Makefile
  Makefile
Labels: approved, lgtm, size/XS

#27 Add an example for installing common service operator on k8s
  docs/install_on_kubernetes.md
Labels: approved, lgtm, size/L

#29 Add toc for install_on_kubernetes
  docs/install_on_kubernetes.md
Labels: approved, lgtm, size/S

#24 Document for common service integration
  docs/common-service-integration.md
  docs/install.md
Labels: approved, lgtm, size/L

#30 Update API to meta-operator
  cmd/manager/main.go
  common/scripts/push-csv.sh
  deploy/olm-catalog/common-service-operator/0.0.3/common-service-operator.v0.0.3.clusterserviceversion.yaml
  deploy/olm-catalog/meta-operator/0.0.3/meta-operator.v0.0.3.clusterserviceversion.yaml
  deploy/olm-catalog/meta-operator/0.0.3/operator.ibm.com_metaoperatorcatalogs_crd.yaml
  deploy/olm-catalog/meta-operator/0.0.3/operator.ibm.com_metaoperatorconfigs_crd.yaml
  deploy/olm-catalog/meta-operator/0.0.3/operator.ibm.com_metaoperatorsets_crd.yaml
  deploy/olm-catalog/meta-operator/meta-operator.package.yaml
  go.mod
  go.sum
  pkg/apis/addtoscheme_operator_v1alpha1.go
  pkg/apis/operator/v1alpha1/zz_generated.openapi.go
  pkg/controller/add_metaoperatorcatalog.go
  pkg/controller/add_metaoperatorconfig.go
  pkg/controller/add_metaoperatorset.go
  pkg/controller/metaoperatorcatalog/metaoperatorcatalog_controller.go
  pkg/controller/metaoperatorconfig/metaoperatorconfig_controller.go
  pkg/controller/metaoperatorset/catalog_status.go
  pkg/controller/metaoperatorset/config_status.go
  pkg/controller/metaoperatorset/metaoperatorset_controller.go
  pkg/controller/metaoperatorset/reconcile_metaoperatorcatalog.go
  pkg/controller/metaoperatorset/reconcile_metaoperatorconfig.go
  pkg/controller/metaoperatorset/set_status.go
  test/config/constants.go
  test/e2e/metaoperatorset_test.go
  test/helpers/helpers.go
  test/testgroups/commonservice.go
  test/testsuits/metaoperatorset.go
Labels: approved, lgtm, size/XL

#31 rename from common service operator to meta operator
  Makefile
  README.md
  build/Dockerfile
  build/bin/entrypoint
  cmd/manager/main.go
  common/scripts/push-csv.sh
  deploy/olm-catalog/common-service-operator/0.0.1/common-service-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/common-service-operator/0.0.1/operator.ibm.com_commonserviceconfigs_crd.yaml
  deploy/olm-catalog/common-service-operator/0.0.1/operator.ibm.com_commonservicesets_crd.yaml
  deploy/olm-catalog/common-service-operator/0.0.1/operator.ibm.com_metaoperators_crd.yaml
  deploy/olm-catalog/common-service-operator/0.0.2/operator.ibm.com_commonserviceconfigs_crd.yaml
  deploy/olm-catalog/common-service-operator/0.0.2/operator.ibm.com_commonservicesets_crd.yaml
  deploy/olm-catalog/common-service-operator/0.0.2/operator.ibm.com_metaoperators_crd.yaml
  deploy/olm-catalog/common-service-operator/0.0.3/common-service-operator.v0.0.3.clusterserviceversion.yaml
  deploy/olm-catalog/common-service-operator/common-service-operator.package.yaml
  deploy/olm-catalog/meta-operator/0.0.1/meta-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/meta-operator/0.0.1/operator.ibm.com_metaoperatorcatalogs_crd.yaml
  deploy/olm-catalog/meta-operator/0.0.1/operator.ibm.com_metaoperatorconfigs_crd.yaml
  deploy/olm-catalog/meta-operator/0.0.1/operator.ibm.com_metaoperatorsets_crd.yaml
  deploy/olm-catalog/meta-operator/0.0.3/meta-operator.v0.0.3.clusterserviceversion.yaml
  deploy/olm-catalog/meta-operator/0.0.3/operator.ibm.com_metaoperatorcatalogs_crd.yaml
  deploy/olm-catalog/meta-operator/0.0.3/operator.ibm.com_metaoperatorconfigs_crd.yaml
  deploy/olm-catalog/meta-operator/0.0.3/operator.ibm.com_metaoperatorsets_crd.yaml
  deploy/olm-catalog/meta-operator/meta-operator.package.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  docs/common-service-integration.md
  docs/e2e.md
  docs/install.md
  docs/install_on_kubernetes.md
  pkg/apis/operator/v1alpha1/zz_generated.openapi.go
  pkg/controller/metaoperatorset/metaoperatorset_controller.go
  pkg/controller/metaoperatorset/reconcile_metaoperatorcatalog.go
  pkg/controller/metaoperatorset/set_status.go
  test/config/constants.go
  test/helpers/helpers.go
  test/testgroups/commonservice.go
Labels: approved, lgtm, size/XXL

#33 minor fix on rename to meta-operator
  docs/install.md
  docs/install_on_kubernetes.md
  pkg/controller/metaoperatorcatalog/metaoperatorcatalog_controller.go
  pkg/controller/metaoperatorset/metaoperatorset_controller.go
  pkg/controller/metaoperatorset/reconcile_metaoperatorcatalog.go
  pkg/util/merge.go
Labels: approved, lgtm, size/S

#32 Remove useless make target
  Makefile
  common/Makefile.common.mk
  common/config/sass-lint.yml
  common/config/tslint.json
  deploy/olm-catalog/meta-operator/0.0.1/meta-operator.v0.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/L

#37 improve wait for function for subscriptions.
  pkg/controller/metaoperatorset/metaoperatorset_controller.go
Labels: approved, lgtm, size/M

#36 remove script for make build
  Makefile
  common/Makefile.common.mk
  common/config/.hadolint.yml
  common/config/.yamllint.yml
  common/config/mdl.rb
  common/scripts/gobuild.sh
Labels: approved, lgtm, size/L

#38 workaround to solve the code-gen path issue
  common/Makefile.common.mk
Labels: approved, lgtm, size/XS

#41 fix makefile issue
  Makefile
Labels: approved, lgtm, size/XS

#43 Upgrade operator sdk
  .gitignore
  common/Makefile.common.mk
  deploy/crds/operator.ibm.com_metaoperatorconfigs_crd.yaml
  deploy/olm-catalog/meta-operator/0.0.1/operator.ibm.com_metaoperatorconfigs_crd.yaml
  go.sum
  pkg/apis/operator/v1alpha1/metaoperatorcatalog_types.go
  pkg/apis/operator/v1alpha1/metaoperatorconfig_types.go
  pkg/apis/operator/v1alpha1/metaoperatorset_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/operator/v1alpha1/zz_generated.openapi.go
  pkg/controller/metaoperatorset/config_status.go
  pkg/controller/metaoperatorset/reconcile_metaoperatorconfig.go
Labels: approved, lgtm, size/M

#49 Pass operator-courier verify
  deploy/olm-catalog/meta-operator/0.0.1/meta-operator.v0.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#52 Add licenses in image
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/S

#53 Add init status for config and catalog
  pkg/apis/operator/v1alpha1/metaoperatorcatalog_types.go
  pkg/apis/operator/v1alpha1/metaoperatorconfig_types.go
  pkg/controller/metaoperatorset/catalog_status.go
  pkg/controller/metaoperatorset/config_status.go
  pkg/controller/metaoperatorset/metaoperatorset_controller.go
Labels: approved, lgtm, size/M

#54 Refactor the layout for meta operator
  docs/design/meta-operator-design.md
  docs/dev/development.md
  docs/dev/e2e.md
  docs/install/common-service-integration.md
  docs/install/install-with-kind.md
  docs/install/install.md
Labels: approved, lgtm, size/XS

#55 Added design for meta operator
  docs/design/meta-operator-design.md
  docs/images/meta-operator-arch.png
Labels: approved, lgtm, size/L

#51 Pass scorecard test
  .osdk-scorecard.yaml
  Makefile
  deploy/olm-catalog/meta-operator/0.0.1/meta-operator.v0.0.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/M

#57 Update config reconcile
  pkg/controller/metaoperatorset/reconcile_metaoperatorconfig.go
Labels: approved, lgtm, size/XS

#61 Add unit test for meta operator catalog controller
  pkg/controller/metaoperatorcatalog/metaoperatorcatalog_controller.go
  pkg/controller/metaoperatorcatalog/metaoperatorcatalog_controller_test.go
Labels: approved, lgtm, size/L

#65 Add Description for catalog
  common/Makefile.common.mk
  deploy/crds/operator.ibm.com_metaoperatorcatalogs_crd.yaml
  deploy/olm-catalog/meta-operator/0.0.1/operator.ibm.com_metaoperatorcatalogs_crd.yaml
  docs/install/common-service-integration.md
  docs/install/install-with-kind.md
  docs/install/install.md
  pkg/apis/operator/v1alpha1/metaoperatorcatalog_types.go
Labels: approved, lgtm, size/S

#67 Watch CatalogSource and CatalogSourceNamespace
  pkg/controller/metaoperatorset/reconcile_metaoperatorcatalog.go
Labels: approved, lgtm, size/XS

#72 Onboard ibm-licensing-operator into meta-operator
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorcatalog_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorconfig_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorset_cr.yaml
Labels: approved, lgtm, size/S

#73 update crs to onboard metering
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorcatalog_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorconfig_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorset_cr.yaml
Labels: approved, lgtm, size/S

#68 add unit test for config
  pkg/controller/metaoperatorconfig/metaoperatorconfig_controller_test.go
Labels: approved, lgtm, size/L

#74 remove placeholder operators
  deploy/crds/operator.ibm.com_metaoperatorsets_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorcatalog_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorconfig_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorset_cr.yaml
  deploy/olm-catalog/meta-operator/0.0.1/meta-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/meta-operator/0.0.1/operator.ibm.com_metaoperatorsets_crd.yaml
  deploy/role.yaml
  pkg/apis/operator/v1alpha1/metaoperatorset_types.go
Labels: approved, lgtm, size/M

#75 Update operator to use operator sdk 0.15.1
  Makefile
  cmd/manager/main.go
  deploy/crds/operator.ibm.com_metaoperatorcatalogs_crd.yaml
  deploy/crds/operator.ibm.com_metaoperatorconfigs_crd.yaml
  deploy/crds/operator.ibm.com_metaoperatorsets_crd.yaml
  go.mod
  go.sum
  pkg/apis/operator/v1alpha1/zz_generated.openapi.go
  pkg/controller/metaoperatorcatalog/metaoperatorcatalog_controller_test.go
  pkg/controller/metaoperatorconfig/metaoperatorconfig_controller_test.go
Labels: approved, lgtm, size/XL

#81 enable multi-ns for meta-operator
  deploy/operator.yaml
  pkg/controller/metaoperatorcatalog/metaoperatorcatalog_controller.go
  pkg/controller/metaoperatorconfig/metaoperatorconfig_controller.go
  pkg/util/seed_cr.go
Labels: approved, lgtm, size/S

#80 Onboard ibm-mongodb operator
  deploy/crds/operator.ibm.com_metaoperatorcatalogs_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorcatalog_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorconfig_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorset_cr.yaml
  deploy/olm-catalog/meta-operator/0.0.1/meta-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/meta-operator/0.0.1/operator.ibm.com_metaoperatorcatalogs_crd.yaml
  deploy/olm-catalog/meta-operator/0.0.1/operator.ibm.com_metaoperatorconfigs_crd.yaml
  deploy/olm-catalog/meta-operator/0.0.1/operator.ibm.com_metaoperatorsets_crd.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  pkg/apis/operator/v1alpha1/metaoperatorcatalog_types.go
  pkg/controller/metaoperatorset/reconcile_metaoperatorcatalog.go
Labels: approved, lgtm, size/M

#82 Fix target namespace issue
  .gitignore
  pkg/controller/metaoperatorset/reconcile_metaoperatorcatalog.go
Labels: approved, lgtm, size/XS

#83 Adding Shikha to OWNER
  OWNERS
Labels: approved, lgtm, size/XS

#69 Onboard cert-manager-operator into meta-operator
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorcatalog_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorconfig_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorset_cr.yaml
  deploy/olm-catalog/meta-operator/0.0.1/meta-operator.v0.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#85 fix permission issue and add placeholder to main operators
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorset_cr.yaml
  deploy/olm-catalog/meta-operator/0.0.1/meta-operator.v0.0.1.clusterserviceversion.yaml
  deploy/role.yaml
Labels: approved, lgtm, size/M

#88 integrate ibm-healthcheck-operator to meta-operator
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorcatalog_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorconfig_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorset_cr.yaml
Labels: approved, lgtm, size/S

#87 Update common service integration
  README.md
  docs/install/common-service-integration.md
Labels: approved, lgtm, size/L

#90 Add unit test for set controller
  go.mod
  go.sum
  pkg/controller/metaoperatorset/metaoperatorset_controller.go
  pkg/controller/metaoperatorset/metaoperatorset_controller_test.go
  pkg/controller/metaoperatorset/reconcile_metaoperatorcatalog.go
Labels: approved, lgtm, size/L

#94 Remove description from set api
  deploy/crds/operator.ibm.com_metaoperatorsets_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorset_cr.yaml
  deploy/olm-catalog/meta-operator/0.0.1/meta-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/meta-operator/0.0.1/operator.ibm.com_metaoperatorsets_crd.yaml
  go.mod
  go.sum
  pkg/apis/operator/v1alpha1/metaoperatorset_types.go
  pkg/controller/metaoperatorset/metaoperatorset_controller_test.go
Labels: approved, lgtm, size/M

#86 integrate iam operator with meta operator
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorcatalog_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorconfig_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorset_cr.yaml
  deploy/olm-catalog/meta-operator/0.0.1/meta-operator.v0.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#98 use ibm-common-services namespace
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorcatalog_cr.yaml
  deploy/olm-catalog/meta-operator/0.0.1/meta-operator.v0.0.1.clusterserviceversion.yaml
  docs/install/common-service-integration.md
Labels: approved, lgtm, size/S

#101 Onboard ibm-management-ingress-operator into meta-operator
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorcatalog_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorconfig_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorset_cr.yaml
  deploy/olm-catalog/meta-operator/0.0.1/meta-operator.v0.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, needs-ok-to-test, size/S

#102 Update csv
  deploy/olm-catalog/meta-operator/0.0.1/meta-operator.v0.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#99 add resolving dependency to onboarding document.
  docs/install/common-service-integration.md
Labels: approved, lgtm, size/L

#100 update wrong link
  docs/install/common-service-integration.md
Labels: approved, lgtm, size/XS

#104 Fix multi operator group issue
  pkg/controller/metaoperatorset/reconcile_metaoperatorcatalog.go
Labels: approved, lgtm, size/M

#105 Disable management ingress as it's not working
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorset_cr.yaml
  deploy/olm-catalog/meta-operator/0.0.1/meta-operator.v0.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#95 Ensure only one metaoperatorconfig and metaoperatorcatalog in one namespace
  pkg/controller/metaoperatorset/metaoperatorset_controller.go
  pkg/controller/metaoperatorset/metaoperatorset_controller_test.go
Labels: approved, lgtm, size/M

#106 Onboard auditlogging-operator with meta-operator
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorcatalog_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorconfig_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorset_cr.yaml
  deploy/olm-catalog/meta-operator/0.0.1/meta-operator.v0.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#97 Onboard Common ui operator
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorcatalog_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorconfig_cr.yaml
  deploy/olm-catalog/meta-operator/0.0.1/meta-operator.v0.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#107 Update csv and config cr error
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorconfig_cr.yaml
  deploy/olm-catalog/meta-operator/0.0.1/meta-operator.v0.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#111 Added github template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm, size/M

#112 Enhance set controller status
  Makefile
  deploy/crds/operator.ibm.com_metaoperatorsets_crd.yaml
  deploy/olm-catalog/meta-operator/0.0.1/operator.ibm.com_metaoperatorsets_crd.yaml
  pkg/apis/operator/v1alpha1/metaoperatorset_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/operator/v1alpha1/zz_generated.openapi.go
  pkg/controller/metaoperatorset/metaoperatorset_controller.go
  pkg/controller/metaoperatorset/reconcile_operand.go
  pkg/controller/metaoperatorset/reconcile_operator.go
  pkg/controller/metaoperatorset/set_status.go
Labels: approved, lgtm, size/L

#108 Onboard ibm-ingress-nginx-operator into meta-operator
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorcatalog_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorconfig_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_metaoperatorset_cr.yaml
  deploy/olm-catalog/meta-operator/0.0.1/meta-operator.v0.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, ok-to-test, size/M

#116 update namespace and list check
  deploy/role_binding.yaml
  pkg/controller/metaoperatorset/metaoperatorset_controller.go
  pkg/util/seed_cr.go
Labels: approved, lgtm, size/M

#115 Update namespace to ibm-common-services
  docs/dev/e2e.md
  docs/install/common-service-integration.md
  docs/install/install-with-kind.md
  docs/install/install.md
Labels: approved, lgtm, size/M

#117 README and Makefile
  Makefile
  README.md
Labels: approved, lgtm, size/S

#120 Update image name to odlm
  Makefile
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  deploy/operator.yaml
Labels: approved, lgtm, size/M

#121 rename metaoperatorcatalog to operandregistry
  Makefile
  deploy/crds/operator.ibm.com_operandregistries_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
  deploy/role.yaml
  docs/install/common-service-integration.md
  docs/install/install-with-kind.md
  docs/install/install.md
  pkg/apis/operator/v1alpha1/operandregistry_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/operator/v1alpha1/zz_generated.openapi.go
  pkg/controller/add_operandregistry.go
  pkg/controller/metaoperatorset/catalog_status.go
  pkg/controller/metaoperatorset/metaoperatorset_controller.go
  pkg/controller/metaoperatorset/metaoperatorset_controller_test.go
  pkg/controller/metaoperatorset/reconcile_operator.go
  pkg/controller/operandregistry/operandregistry_controller.go
  pkg/controller/operandregistry/operandregistry_controller_test.go
  test/helpers/helpers.go
  test/testgroups/commonservice.go
  test/testsuits/metaoperatorset.go
Labels: approved, lgtm, size/XL

#118 create operator group for test csv
  test/helpers/helpers.go
Labels: approved, lgtm, size/M

#122 rename metaoperatorset to operandrequest
  Makefile
  deploy/crds/operator.ibm.com_operandrequests_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
  deploy/role.yaml
  docs/design/operand-deployment-lifecycle-manager.md
  docs/install/common-service-integration.md
  docs/install/install-with-kind.md
  docs/install/install.md
  pkg/apis/operator/v1alpha1/operandrequest_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/operator/v1alpha1/zz_generated.openapi.go
  pkg/controller/add_operandrequest.go
  pkg/controller/operandrequest/config_status.go
  pkg/controller/operandrequest/operandrequest_controller.go
  pkg/controller/operandrequest/operandrequest_controller_test.go
  pkg/controller/operandrequest/reconcile_operand.go
  pkg/controller/operandrequest/reconcile_operator.go
  pkg/controller/operandrequest/registry_status.go
  pkg/controller/operandrequest/request_status.go
  test/e2e/operandrequest_test.go
  test/helpers/helpers.go
  test/testgroups/commonservice.go
  test/testsuits/operandrequest.go
Labels: approved, lgtm, size/XL

#124 Generate new csv
  README.md
  deploy/crds/operator.ibm.com_metaoperatorconfigs_crd.yaml
  deploy/crds/operator.ibm.com_operandconfigs_crd.yaml
  deploy/crds/operator.ibm.com_operandregistries_crd.yaml
  deploy/crds/operator.ibm.com_operandrequests_crd.yaml
  deploy/olm-catalog/meta-operator/meta-operator.package.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operator.ibm.com_operandconfigs_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operator.ibm.com_operandregistries_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operator.ibm.com_operandrequests_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/operand-deployment-lifecycle-manager.package.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  pkg/apis/operator/v1alpha1/operandconfig_types.go
  pkg/apis/operator/v1alpha1/operandregistry_types.go
  pkg/apis/operator/v1alpha1/operandrequest_types.go
Labels: approved, lgtm, size/XL

#125 Update config controller seed cr file name
  pkg/apis/operator/v1alpha1/zz_generated.openapi.go
  pkg/controller/operandconfig/operandconfig_controller.go
  pkg/controller/operandconfig/operandconfig_controller_test.go
  pkg/controller/operandregistry/operandregistry_controller.go
  pkg/controller/operandrequest/operandrequest_controller.go
Labels: approved, lgtm, size/M

#126 Some clean up for meta-operator to ODLM
  .osdk-scorecard.yaml
  build/bin/entrypoint
  cmd/manager/main.go
  common/Makefile.common.mk
  common/scripts/push-csv.sh
  docs/install/common-service-integration.md
  docs/install/install-with-kind.md
  docs/install/install.md
  pkg/controller/operandconfig/operandconfig_controller_test.go
  pkg/controller/operandregistry/operandregistry_controller_test.go
  pkg/controller/operandrequest/operandrequest_controller_test.go
  pkg/controller/operandrequest/reconcile_operator.go
  test/e2e/operandrequest_test.go
  test/helpers/helpers.go
Labels: approved, lgtm, size/M

#128 onboarding catalog operator
  deploy/crds/operator.ibm.com_v1alpha1_operandconfig_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#129 Update scorecard
  .osdk-scorecard.yaml
  README.md
  deploy/crds/operator.ibm.com_operandconfigs_crd.yaml
  deploy/crds/operator.ibm.com_operandregistries_crd.yaml
  deploy/crds/operator.ibm.com_operandrequests_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
  docs/design/operand-deployment-lifecycle-manager.md
  docs/dev/scorecard.md
  pkg/apis/operator/v1alpha1/operandconfig_types.go
  pkg/apis/operator/v1alpha1/operandregistry_types.go
  pkg/apis/operator/v1alpha1/operandrequest_types.go
  pkg/apis/operator/v1alpha1/zz_generated.openapi.go
  pkg/controller/operandrequest/operandrequest_controller.go
Labels: approved, lgtm, size/L

#130 update auditLogging
  deploy/crds/operator.ibm.com_v1alpha1_operandconfig_cr.yaml
Labels: approved, lgtm, size/XS

#131 Do not use meta operator concept.
  README.md
  docs/install/common-service-integration.md
  docs/install/install-with-kind.md
  docs/install/install.md
  test/config/constants.go
  test/helpers/helpers.go
  test/testgroups/commonservice.go
Labels: approved, lgtm, size/M

#132 Clean up for odlm concept
  docs/install/common-service-integration.md
  docs/install/install.md
  test/config/constants.go
  test/e2e/operandrequest_test.go
  test/helpers/helpers.go
  test/testgroups/commonservice.go
  test/testsuits/operandrequest.go
Labels: approved, lgtm, size/L

#135 Clean up meta-operator concept
  deploy/crds/operator.ibm.com_operandrequests_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operator.ibm.com_operandconfigs_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operator.ibm.com_operandregistries_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operator.ibm.com_operandrequests_crd.yaml
  pkg/apis/operator/v1alpha1/operandrequest_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/operator/v1alpha1/zz_generated.openapi.go
  pkg/controller/operandconfig/operandconfig_controller.go
  pkg/controller/operandregistry/operandregistry_controller.go
  pkg/controller/operandregistry/operandregistry_controller_test.go
  pkg/controller/operandrequest/operandrequest_controller.go
  pkg/controller/operandrequest/operandrequest_controller_test.go
  pkg/controller/operandrequest/reconcile_operand.go
  pkg/controller/operandrequest/reconcile_operator.go
  test/helpers/helpers.go
Labels: approved, lgtm, size/L

#136 Enhance logs for tracking installation process
  deploy/crds/operator.ibm.com_operandconfigs_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operator.ibm.com_operandconfigs_crd.yaml
  pkg/apis/operator/v1alpha1/operandconfig_types.go
  pkg/controller/operandconfig/operandconfig_controller.go
  pkg/controller/operandregistry/operandregistry_controller.go
  pkg/controller/operandrequest/operandrequest_controller.go
  pkg/controller/operandrequest/reconcile_operand.go
  pkg/controller/operandrequest/reconcile_operator.go
  pkg/util/merge.go
  pkg/util/seed_cr.go
  test/config/constants.go
  test/helpers/helpers.go
Labels: approved, lgtm, size/M

#137 fix operatorgroup create
  pkg/controller/operandrequest/reconcile_operator.go
  test/helpers/helpers.go
Labels: approved, lgtm, size/S

#141 Remove openapi gen
  common/Makefile.common.mk
  go.mod
  pkg/apis/operator/v1alpha1/zz_generated.openapi.go
Labels: approved, lgtm, size/L

#139 Enhance integration doc
  docs/install/common-service-integration.md
Labels: approved, lgtm, size/S

#146 Enhance operand request condition status
  deploy/crds/operator.ibm.com_operandrequests_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operator.ibm.com_operandrequests_crd.yaml
  pkg/apis/operator/v1alpha1/operandrequest_types.go
  pkg/controller/operandrequest/operandrequest_controller.go
  pkg/controller/operandrequest/operandrequest_controller_test.go
  pkg/controller/operandrequest/reconcile_operand.go
  pkg/controller/operandrequest/reconcile_operator.go
  pkg/controller/operandrequest/request_status.go
Labels: approved, lgtm, size/L

#148 Add scope for operand registry crd
  deploy/crds/operator.ibm.com_operandregistries_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operator.ibm.com_operandregistries_crd.yaml
  go.sum
  pkg/apis/operator/v1alpha1/operandregistry_types.go
Labels: approved, lgtm, size/M

#140 onboarding platform-api
  deploy/crds/operator.ibm.com_v1alpha1_operandconfig_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#151 Set default value for OperandRegistry
  pkg/apis/operator/v1alpha1/operandregistry_types.go
  pkg/controller/operandregistry/operandregistry_controller.go
Labels: approved, lgtm, size/S

#150 Onboard helm api, helm repo, management repo components
  deploy/crds/operator.ibm.com_v1alpha1_operandconfig_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#153 Enhance uninstall
  common/config/.golangci.yml
  go.mod
  go.sum
  pkg/controller/operandrequest/config_status.go
  pkg/controller/operandrequest/operandrequest_controller.go
  pkg/controller/operandrequest/operandrequest_controller_test.go
  pkg/controller/operandrequest/reconcile_operand.go
  pkg/controller/operandrequest/reconcile_operator.go
  test/helpers/helpers.go
Labels: approved, lgtm, size/L
