Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2020-09, with the labels that each got.

#509 Update operator-sdk version
  README.md
Labels: approved, lgtm, size/XS

#506 enhance the unit test to increase the code coverage
  Makefile
  common/Makefile.common.mk
  controllers/common/fetch.go
  controllers/operandbindinfo_controller_test.go
  controllers/operandconfig_controller_test.go
  controllers/operandregistry_controller_test.go
  controllers/operandrequest_controller_test.go
  controllers/suite_test.go
  controllers/testutil/test_data.go
  go.mod
  go.sum
Labels: approved, lgtm, size/XL

#510 Avoid conflict when CR and status update
  controllers/operandconfig_controller.go
  controllers/operandregistry_controller.go
  controllers/operandrequest_controller.go
  controllers/reconcile_operand.go
  controllers/reconcile_operator.go
Labels: approved, lgtm, size/L

#507 Add a new fetch csv method for delete
  controllers/common/fetch.go
  controllers/operandrequest_controller_test.go
  controllers/reconcile_operator.go
  controllers/testutil/test_data.go
  go.mod
Labels: approved, lgtm, size/L

#511 Fix two typos
  api/v1alpha1/operandregistry_types.go
  api/v1alpha1/operandrequest_types.go
Labels: approved, lgtm, size/XS

#513 Add label for ibm certification
  bundle/manifests/operator.ibm.com_operandbindinfos.yaml
  bundle/manifests/operator.ibm.com_operandconfigs.yaml
  bundle/manifests/operator.ibm.com_operandregistries.yaml
  bundle/manifests/operator.ibm.com_operandrequests.yaml
  config/crd/kustomization.yaml
  config/crd/patches/label_in_operandbindinfos.yaml
  config/crd/patches/label_in_operandconfigs.yaml
  config/crd/patches/label_in_operandregistries.yaml
  config/crd/patches/label_in_operandrequests.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.4/operator.ibm.com_operandbindinfos_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.4/operator.ibm.com_operandconfigs_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.4/operator.ibm.com_operandregistries_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.4/operator.ibm.com_operandrequests_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.3.0/operator.ibm.com_operandbindinfos_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.3.0/operator.ibm.com_operandconfigs_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.3.0/operator.ibm.com_operandregistries_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.3.0/operator.ibm.com_operandrequests_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.3.1/operator.ibm.com_operandbindinfos_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.3.1/operator.ibm.com_operandconfigs_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.3.1/operator.ibm.com_operandregistries_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.3.1/operator.ibm.com_operandrequests_crd.yaml
Labels: approved, lgtm, size/L

#514 Reconcile operand Request every 30 mins
  controllers/operandrequest_controller.go
Labels: approved, lgtm, size/XS

#515 Revert "enhance fetch csv method for delete (#507)"
  controllers/common/fetch.go
  controllers/operandrequest_controller_test.go
  controllers/reconcile_operator.go
  controllers/testutil/test_data.go
  go.mod
Labels: approved, lgtm, size/L
