Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2020-01, with the labels that each got.

#1 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#8 add x permission for install-operator-sdk.sh
  common/scripts/install-operator-sdk.sh
Labels: approved, lgtm, size/XS

#7 add metaOperator status
  .gitignore
  Makefile
  deploy/crds/operator.ibm.com_metaoperators_crd.yaml
  deploy/olm-catalog/common-service-operator/0.0.3/operator.ibm.com_metaoperators_crd.yaml
  pkg/apis/operator/v1alpha1/metaoperator_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/operator/v1alpha1/zz_generated.openapi.go
  pkg/controller/commonserviceset/commonserviceset_controller.go
  pkg/controller/commonserviceset/metaoperator_status.go
Labels: approved, lgtm, size/L

#10 Add Jin into OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#13 Update api to the public github
  cmd/manager/main.go
  deploy/olm-catalog/common-service-operator/0.0.1/common-service-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/common-service-operator/0.0.2/common-service-operator.v0.0.2.clusterserviceversion.yaml
  deploy/olm-catalog/common-service-operator/0.0.3/common-service-operator.v0.0.3.clusterserviceversion.yaml
  go.mod
  pkg/apis/addtoscheme_operator_v1alpha1.go
  pkg/controller/add_commonserviceconfig.go
  pkg/controller/add_commonserviceset.go
  pkg/controller/add_metaoperator.go
  pkg/controller/commonserviceconfig/commonserviceconfig_controller.go
  pkg/controller/commonserviceset/commonserviceset_controller.go
  pkg/controller/commonserviceset/config_status.go
  pkg/controller/commonserviceset/metaoperator_status.go
  pkg/controller/commonserviceset/set_status.go
  pkg/controller/metaoperator/metaoperator_controller.go
  test/e2e/commonserviceset_test.go
Labels: approved, lgtm, size/L

#15 Push csv to quay.io
  Makefile
  common/config/.yamllint.yml
  common/scripts/push-csv.sh
Labels: approved, lgtm, size/M

#12 Update install readme
  deploy/crds/operator.ibm.com_metaoperators_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_metaoperator_cr.yaml
  deploy/olm-catalog/common-service-operator/0.0.3/common-service-operator.v0.0.3.clusterserviceversion.yaml
  deploy/olm-catalog/common-service-operator/0.0.3/operator.ibm.com_metaoperators_crd.yaml
  docs/install.md
  pkg/apis/operator/v1alpha1/metaoperator_types.go
Labels: approved, lgtm, size/L

#17 seperator codes and enable gocyclo
  common/config/.golangci.yml
  deploy/crds/operator.ibm.com_commonservicesets_crd.yaml
  deploy/olm-catalog/common-service-operator/0.0.3/operator.ibm.com_commonservicesets_crd.yaml
  pkg/apis/operator/v1alpha1/commonserviceset_types.go
  pkg/controller/commonserviceset/commonserviceset_controller.go
  pkg/controller/commonserviceset/reconcile_commonserviceconfig.go
  pkg/controller/commonserviceset/reconcile_metaoperatpor.go
  pkg/controller/commonserviceset/set_status.go
Labels: approved, lgtm, size/XL

#19 Updated install to clarify ns name can be customized.
  docs/install.md
Labels: approved, lgtm, size/S
