Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2020-11, with the labels that each got.

#540 Update namespace member in NamespaceScope instance
  controllers/constant/constant.go
  controllers/operandrequest_controller.go
  controllers/suite_test.go
  controllers/util/get_env.go
  controllers/util/util.go
  controllers/util/util_test.go
  go.mod
  go.sum
  main.go
Labels: approved, lgtm, size/L

#542 add watch namespace to ODLM
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manager/manager.yaml
  controllers/k8sutil/cache.go
  controllers/operandrequest_controller.go
  controllers/util/util.go
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.4.0/operand-deployment-lifecycle-manager.v1.4.0.clusterserviceversion.yaml
  go.mod
  main.go
Labels: approved, lgtm, size/M

#541 Push image to quay.io
  Makefile
  common/scripts/quay_config_docker.sh
Labels: approved, lgtm, size/M

#544 update ODLM cache
  controllers/k8sutil/cache.go
  main.go
Labels: approved, lgtm, size/M

#545 update error messages and avoid status update error
  controllers/common/fetch.go
  controllers/k8sutil/cache.go
  controllers/operandbindinfo_controller.go
  controllers/operandconfig_controller.go
  controllers/operandregistry_controller.go
  controllers/operandrequest_controller.go
  controllers/reconcile_operator.go
  controllers/util/merge.go
  controllers/util/util.go
  controllers/util/util_test.go
  main.go
Labels: approved, lgtm, size/L

#549 update cluster role
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/rbac/role.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.4.0/operand-deployment-lifecycle-manager.v1.4.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#547 update warning message when service can't be found in OperandConfig
  controllers/operandrequest_controller.go
  controllers/reconcile_operand.go
Labels: approved, lgtm, size/S

#548 rename secret configmap when operandrequest is in the same namespace as operandbindinfo
  controllers/operandbindinfo_controller.go
Labels: approved, lgtm, size/S

#550 don't remove namespaces from the namespace member list
  controllers/operandrequest_controller.go
Labels: approved, lgtm, size/S

#551 update the name of the managed namespace scope CR
  controllers/constant/constant.go
Labels: approved, lgtm, size/XS

#552 remove namespace from nss when there is no operandrequest in that ns
  controllers/operandrequest_controller.go
Labels: approved, lgtm, size/S

#553 Remove Quay push to avoid overwriting CICD push
  Makefile
Labels: approved, lgtm, size/XS

#554 remove package manifest
  Makefile
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.4.0/operand-deployment-lifecycle-manager.v1.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.4.0/operator.ibm.com_operandbindinfos_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.4.0/operator.ibm.com_operandconfigs_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.4.0/operator.ibm.com_operandregistries_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.4.0/operator.ibm.com_operandrequests_crd.yaml
  docs/install/install-with-kind.md
  docs/install/install-with-ocp-3.11.md
  docs/install/install.md
Labels: approved, lgtm, size/XL

#556 remove replaces
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#555 Update csv version in package yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/operand-deployment-lifecycle-manager.package.yaml
Labels: approved, size/XS

#559 remove crds from .gitignore
  .gitignore
Labels: approved, lgtm, size/XS

#557 Check alm-examples empty
  controllers/operandconfig_controller.go
Labels: approved, lgtm

#558 reduce logs from bindinfo
  controllers/operandbindinfo_controller.go
  controllers/reconcile_operand.go
Labels: approved, lgtm, size/S

#560 bump version to 1.4.1
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#562 condition status update
  api/v1alpha1/operandrequest_types.go
Labels: approved, lgtm, size/S

#563 only reconcile operandrequest when spec change
  controllers/operandrequest_controller.go
Labels: approved, lgtm, size/XS
