Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2020-05, with the labels that each got.

#373 Revert "Add v1 api (#371)"
  Makefile
  deploy/crds/operator.ibm.com_operandbindinfos_crd.yaml
  deploy/crds/operator.ibm.com_operandconfigs_crd.yaml
  deploy/crds/operator.ibm.com_operandregistries_crd.yaml
  deploy/crds/operator.ibm.com_operandrequests_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_operandconfig_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operand-deployment-lifecycle-manager.v1.2.0.clusterserviceversion.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operator.ibm.com_operandbindinfos_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operator.ibm.com_operandconfigs_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operator.ibm.com_operandregistries_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operator.ibm.com_operandrequests_crd.yaml
  pkg/apis/addtoscheme_operator_v1.go
  pkg/apis/operator/v1/doc.go
  pkg/apis/operator/v1/operandconfig_types.go
  pkg/apis/operator/v1/operandregistry_types.go
  pkg/apis/operator/v1/operandrequest_types.go
  pkg/apis/operator/v1/register.go
  pkg/apis/operator/v1/zz_generated.deepcopy.go
  pkg/apis/operator/v1alpha1/operandbindinfo_types.go
  pkg/apis/operator/v1alpha1/operandconfig_types.go
  pkg/apis/operator/v1alpha1/operandregistry_types.go
  pkg/apis/operator/v1alpha1/operandrequest_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/operandbindinfo/bindInfo_status.go
  pkg/controller/operandbindinfo/operandbindinfo_controller.go
  pkg/controller/operandbindinfo/operandbindinfo_controller_test.go
  pkg/controller/operandconfig/operandconfig_controller.go
  pkg/controller/operandconfig/operandconfig_controller_test.go
  pkg/controller/operandregistry/operandregistry_controller.go
  pkg/controller/operandregistry/operandregistry_controller_test.go
  pkg/controller/operandrequest/config_status.go
  pkg/controller/operandrequest/operandrequest_controller.go
  pkg/controller/operandrequest/operandrequest_controller_test.go
  pkg/controller/operandrequest/reconcile_operand.go
  pkg/controller/operandrequest/reconcile_operator.go
  pkg/controller/operandrequest/registry_status.go
  pkg/controller/operandrequest/request_status.go
  test/e2e/odlm_test.go
  test/helpers/helpers.go
  test/testgroups/operandbindinfo_group.go
  test/testgroups/operandconfig_group.go
  test/testgroups/operandregistry_group.go
  test/testgroups/operandrequest_group.go
Labels: approved, lgtm, size/XXL

#375 fix the wrong path issue
  docs/install/install.md
Labels: approved, lgtm, size/XS

#376 add name to error message
  pkg/controller/operandrequest/reconcile_operand.go
Labels: approved, lgtm, size/XS

#378 Bump metering version to 3.4.0
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operand-deployment-lifecycle-manager.v1.2.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#377 Update log messages
  pkg/controller/operandbindinfo/operandbindinfo_controller.go
  pkg/controller/operandconfig/operandconfig_controller.go
  pkg/controller/operandregistry/operandregistry_controller.go
  pkg/controller/operandrequest/operandrequest_controller.go
  pkg/controller/operandrequest/reconcile_operand.go
  pkg/controller/operandrequest/reconcile_operator.go
Labels: approved, lgtm, size/M

#379 Ibm certify
  README.md
  deploy/crds/operator.ibm.com_operandbindinfos_crd.yaml
  deploy/crds/operator.ibm.com_operandconfigs_crd.yaml
  deploy/crds/operator.ibm.com_operandregistries_crd.yaml
  deploy/crds/operator.ibm.com_operandrequests_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operator.ibm.com_operandbindinfos_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operator.ibm.com_operandconfigs_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operator.ibm.com_operandregistries_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operator.ibm.com_operandrequests_crd.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
Labels: approved, lgtm, size/M

#381 Deduplicate namespace in the operandbindinfo status
  pkg/controller/operandbindinfo/bindInfo_status.go
Labels: approved, lgtm, ok-to-test, size/S

#383 Fix cv lint error
  README.md
  deploy/crds/operator.ibm.com_v1alpha1_operandconfig_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operand-deployment-lifecycle-manager.v1.2.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/M

#384 Update the images tag to digest
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operand-deployment-lifecycle-manager.v1.2.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#386 Revert to use image tag
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operand-deployment-lifecycle-manager.v1.2.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#388 create beta channel and update tag to digest
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operand-deployment-lifecycle-manager.v1.2.0.clusterserviceversion.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/operand-deployment-lifecycle-manager.package.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#390 update bindinfo status
  pkg/controller/operandbindinfo/bindInfo_status.go
  pkg/controller/operandbindinfo/operandbindinfo_controller.go
Labels: approved, lgtm, size/S

#391 continue the loop when can't get request
  pkg/controller/operandbindinfo/operandbindinfo_controller.go
Labels: approved, lgtm, size/XS

#389 Bump version to 1.2.1
  Makefile
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.1/operand-deployment-lifecycle-manager.v1.2.1.clusterserviceversion.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.1/operator.ibm.com_operandbindinfos_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.1/operator.ibm.com_operandconfigs_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.1/operator.ibm.com_operandregistries_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.1/operator.ibm.com_operandrequests_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/operand-deployment-lifecycle-manager.package.yaml
  version/version.go
Labels: approved, lgtm, size/XXL

#392 inject vcs info to docker image
  Makefile
Labels: approved, lgtm, size/XS

#394 Using 1.2.0 crds for 1.2.1
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.1/operator.ibm.com_operandregistries_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.1/operator.ibm.com_operandrequests_crd.yaml
Labels: approved, lgtm, size/S
