Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2020-07, with the labels that each got.

#451 Move all the default value set into the fetch method
  pkg/apis/operator/v1alpha1/operandregistry_types.go
  pkg/apis/operator/v1alpha1/operandrequest_types.go
  pkg/controller/common/fetch.go
  pkg/controller/operandconfig/operandconfig_controller.go
  pkg/controller/operandregistry/operandregistry_controller.go
  pkg/controller/operandrequest/config_status.go
  pkg/controller/operandrequest/operandrequest_controller.go
  pkg/controller/operandrequest/operandrequest_controller_test.go
  pkg/controller/operandrequest/reconcile_operand.go
  pkg/controller/operandrequest/reconcile_operator.go
Labels: approved, lgtm, size/L

#452 Check catalog source status
  pkg/apis/operator/v1alpha1/operandregistry_types.go
  pkg/apis/operator/v1alpha1/operandrequest_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/operandbindinfo/operandbindinfo_controller.go
  pkg/controller/operandregistry/operandregistry_controller.go
  pkg/controller/operandregistry/operandregistry_controller_test.go
  pkg/controller/operandrequest/operandrequest_controller.go
  pkg/controller/operandrequest/reconcile_operand.go
  pkg/controller/operandrequest/reconcile_operator.go
Labels: approved, lgtm, size/L

#454 Fix fresh member status issue
  pkg/apis/operator/v1alpha1/operandrequest_types.go
Labels: approved, lgtm, size/S

#456 Remove excess cr update
  pkg/controller/operandbindinfo/operandbindinfo_controller.go
  pkg/controller/operandrequest/operandrequest_controller.go
  pkg/controller/operandrequest/reconcile_operand.go
  pkg/controller/operandrequest/reconcile_operator.go
Labels: approved, lgtm, size/M

#458 Add label to prevent subscription and CR uninstall
  pkg/constant/constant.go
  pkg/controller/operandrequest/operandrequest_controller.go
  pkg/controller/operandrequest/operandrequest_controller_test.go
  pkg/controller/operandrequest/reconcile_operand.go
  pkg/controller/operandrequest/reconcile_operator.go
Labels: approved, lgtm, size/M

#461 Enable some ut with new code
  pkg/controller/operandregistry/operandregistry_controller_test.go
  pkg/controller/operandrequest/operandrequest_controller_test.go
Labels: approved, lgtm, size/L

#462 Enhance operator e2e test
  test/helpers/helpers.go
  test/testgroups/operandbindinfo_group.go
  test/testgroups/operandconfig_group.go
  test/testgroups/operandregistry_group.go
  test/testgroups/operandrequest_group.go
Labels: approved, lgtm, size/S

#460 Check the operator generated from the OCP console
  pkg/controller/common/fetch.go
  pkg/controller/operandrequest/reconcile_operand.go
  pkg/controller/operandrequest/reconcile_operator.go
Labels: approved, lgtm, size/M

#463 Fix operator absent issue
  pkg/controller/operandrequest/operandrequest_controller.go
  pkg/controller/operandrequest/operandrequest_controller_test.go
  pkg/controller/operandrequest/reconcile_operator.go
Labels: approved, lgtm, size/M

#465 Separate OperandConfig status reconciliation from the OperandRequest controller
  pkg/apis/operator/v1alpha1/operandconfig_types.go
  pkg/apis/operator/v1alpha1/operandrequest_types.go
  pkg/controller/common/fetch.go
  pkg/controller/operandconfig/operandconfig_controller.go
  pkg/controller/operandconfig/operandconfig_controller_test.go
  pkg/controller/operandrequest/config_status.go
  pkg/controller/operandrequest/operandrequest_controller_test.go
  pkg/controller/operandrequest/reconcile_operand.go
  pkg/controller/operandrequest/reconcile_operator.go
Labels: approved, lgtm, size/XL

#467 Fix OperandConfig reconcile cannot stop issue
  pkg/apis/operator/v1alpha1/operandconfig_types.go
  pkg/controller/operandbindinfo/operandbindinfo_controller.go
  pkg/controller/operandconfig/operandconfig_controller.go
  pkg/controller/operandregistry/operandregistry_controller.go
  pkg/controller/operandrequest/operandrequest_controller.go
  pkg/controller/operandrequest/reconcile_operand.go
  pkg/controller/operandrequest/reconcile_operator.go
Labels: approved, lgtm, size/M

#469 Remove finalizer for config and registry
  pkg/controller/operandconfig/operandconfig_controller.go
  pkg/controller/operandregistry/operandregistry_controller.go
Labels: approved, lgtm, size/M

#470 update odlm image digest in the beta channel
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.3/operand-deployment-lifecycle-manager.v1.2.3.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#472 add install mode to ODLM
  docs/design/operand-deployment-lifecycle-manager.md
Labels: approved, lgtm, size/XS

#474 Check catalog source status every 10 mins
  pkg/controller/operandregistry/operandregistry_controller.go
Labels: approved, lgtm, size/M

#479 Update odlm image digest for csv v1.2.3
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.3/operand-deployment-lifecycle-manager.v1.2.3.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#480 Promote stable-v1 channel to use CSV 1.2.3
  deploy/olm-catalog/operand-deployment-lifecycle-manager/operand-deployment-lifecycle-manager.package.yaml
Labels: approved, lgtm, size/XS

#477 Delete copies when the bindinfo is deleted
  pkg/controller/operandbindinfo/operandbindinfo_controller.go
  pkg/controller/operandbindinfo/operandbindinfo_controller_test.go
Labels: approved, lgtm, size/M

#473 Update e2e test
  pkg/controller/operandbindinfo/operandbindinfo_controller.go
  pkg/controller/operandrequest/operandrequest_controller.go
  test/helpers/helpers.go
  test/helpers/operandbindinfo.go
  test/helpers/operandconfig.go
  test/helpers/operandregistry.go
  test/helpers/operandrequest.go
  test/helpers/templates.go
  test/testgroups/operandbindinfo_group.go
  test/testgroups/operandconfig_group.go
  test/testgroups/operandregistry_group.go
  test/testgroups/operandrequest_group.go
Labels: approved, lgtm, size/XXL
