Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2020-12, with the labels that each got.

#568 bump operator version to 1.5.0
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#569 bump version to 1.4.2
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#567 check if the service exists in the opcon, then update the status
  controllers/operandconfig_controller.go
Labels: approved, lgtm, size/XS

#565 Use label kubernetes.io
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manager/manager.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operand-deployment-lifecycle-manager.v1.2.0.clusterserviceversion.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.1/operand-deployment-lifecycle-manager.v1.2.1.clusterserviceversion.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.2/operand-deployment-lifecycle-manager.v1.2.2.clusterserviceversion.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.3/operand-deployment-lifecycle-manager.v1.2.3.clusterserviceversion.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.4/operand-deployment-lifecycle-manager.v1.2.4.clusterserviceversion.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.3.0/operand-deployment-lifecycle-manager.v1.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.3.1/operand-deployment-lifecycle-manager.v1.3.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#566 Move add namespace member to the front of update
  controllers/operandrequest_controller.go
  go.mod
Labels: approved, lgtm, size/M

#571 tidy go.mod
  controllers/operandrequest_controller.go
  go.mod
Labels: approved, lgtm, size/XS

#572 refactor ODLM
  controllers/operandbindinfo/operandbindinfo_controller.go
  controllers/operandbindinfo/operandbindinfo_controller_test.go
  controllers/operandbindinfo/operandbindinfo_suite_test.go
  controllers/operandconfig/operandconfig_controller.go
  controllers/operandconfig/operandconfig_controller_test.go
  controllers/operandconfig/operandconfig_suite_test.go
  controllers/operandregistry/operandregistry_controller.go
  controllers/operandregistry/operandregistry_controller_test.go
  controllers/operandregistry/operandregistry_suite_test.go
  controllers/operandrequest/operandrequest_controller.go
  controllers/operandrequest/operandrequest_controller_suit_test.go
  controllers/operandrequest/operandrequest_controller_test.go
  controllers/operandrequest/reconcile_operand.go
  controllers/operandrequest/reconcile_operator.go
  controllers/testutil/test_data.go
  controllers/testutil/test_util.go
  main.go
Labels: approved, lgtm, size/XXL

#578 operandconfig status update
  controllers/operandconfig/operandconfig_controller.go
Labels: approved, lgtm, size/S

#579 Shrink permissions for ODLM CRDs
  bundle.Dockerfile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  common/Makefile.common.mk
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/rbac/role.yaml
Labels: approved, lgtm, size/M

#580 Only update status once in the reconciliation
  api/v1alpha1/operandconfig_types.go
  api/v1alpha1/operandregistry_types.go
  controllers/operandbindinfo/operandbindinfo_controller.go
  controllers/operandconfig/operandconfig_controller.go
  controllers/operandregistry/operandregistry_controller.go
  controllers/operandrequest/operandrequest_controller.go
Labels: approved, lgtm, size/M

#581 update operandrequest status when registry notfound
  api/v1alpha1/operandrequest_types.go
  controllers/operandrequest/operandrequest_controller.go
  controllers/operandrequest/reconcile_operand.go
  controllers/operandrequest/reconcile_operator.go
Labels: approved, lgtm, size/L

#583 Use value as the operand Spec
  api/v1alpha1/operandrequest_types.go
  api/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XS
