Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2020-06, with the labels that each got.

#409 bump stablev-1 channel to use CSV 1.2.1
  deploy/olm-catalog/operand-deployment-lifecycle-manager/operand-deployment-lifecycle-manager.package.yaml
Labels: approved, lgtm, size/XS

#407 remove the timeout for the installplan
  go.sum
  pkg/apis/operator/v1alpha1/operandregistry_types.go
  pkg/apis/operator/v1alpha1/operandrequest_types.go
  pkg/controller/operandrequest/operandrequest_controller.go
  pkg/controller/operandrequest/operandrequest_controller_test.go
  pkg/controller/operandrequest/reconcile_operand.go
  pkg/controller/operandrequest/reconcile_operator.go
Labels: approved, lgtm, size/L

#402 remove package dependency bou.ke/monkey
  go.mod
  go.sum
Labels: approved, kind/bug, lgtm, size/XS

#400 enhance delete subscription
  pkg/controller/operandrequest/reconcile_operator.go
Labels: approved, enhancement, lgtm, size/S

#415 Watch OperandRegisty spec change in OperandRequest controller
  pkg/apis/operator/v1alpha1/operandregistry_types.go
  pkg/controller/operandconfig/operandconfig_controller.go
  pkg/controller/operandregistry/operandregistry_controller.go
  pkg/controller/operandrequest/operandrequest_controller.go
Labels: approved, enhancement, feature, lgtm, size/M

#416 Watch OperandRequest status change in OperandRegistry controller
  pkg/apis/operator/v1alpha1/operandrequest_types.go
  pkg/controller/operandregistry/operandregistry_controller.go
Labels: approved, enhancement, feature, lgtm, size/M

#420 Add watch to request and bindinfo reconcile
  pkg/controller/operandbindinfo/operandbindinfo_controller.go
  pkg/controller/operandconfig/operandconfig_controller.go
  pkg/controller/operandconfig/operandconfig_controller_test.go
  pkg/controller/operandregistry/operandregistry_controller.go
  pkg/controller/operandregistry/operandregistry_controller_test.go
  pkg/controller/operandrequest/operandrequest_controller.go
Labels: approved, lgtm, size/L

#423 Fix make check error SA5011: possible nil pointer dereference
  pkg/controller/operandrequest/reconcile_operand.go
Labels: approved, lgtm, size/XS

#425 Cleanup OperandConfig status
  pkg/controller/operandrequest/reconcile_operand.go
Labels: approved, lgtm, size/M

#424 Update documents using jenkins as example
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.2/operand-deployment-lifecycle-manager.v1.2.2.clusterserviceversion.yaml
  deploy/operator.yaml
  docs/design/operand-deployment-lifecycle-manager.md
Labels: approved, lgtm, size/L

#428 Enhance request member status
  Makefile
  pkg/apis/operator/v1alpha1/operandregistry_types.go
  pkg/apis/operator/v1alpha1/operandrequest_types.go
  pkg/controller/operandbindinfo/operandbindinfo_controller_test.go
  pkg/controller/operandregistry/operandregistry_controller.go
  pkg/controller/operandregistry/operandregistry_controller_test.go
  pkg/controller/operandrequest/operandrequest_controller.go
  pkg/controller/operandrequest/operandrequest_controller_test.go
  pkg/controller/operandrequest/reconcile_operand.go
  pkg/controller/operandrequest/reconcile_operator.go
  pkg/controller/operandrequest/registry_status.go
  pkg/controller/operandrequest/request_status.go
  test/helpers/helpers.go
  test/testgroups/operandregistry_group.go
  test/testgroups/operandrequest_group.go
Labels: approved, lgtm, size/XL

#432 Update finializer management
  pkg/controller/operandrequest/operandrequest_controller.go
Labels: approved, lgtm, size/M

#437 Add comments and only wtach operandregistry changing
  pkg/controller/operandregistry/operandregistry_controller.go
Labels: approved, lgtm, size/XS

#440 Fresh member status
  pkg/apis/operator/v1alpha1/operandrequest_types.go
  pkg/controller/operandrequest/reconcile_operator.go
Labels: approved, lgtm, size/M

#429 support operator install mode: cluster and namespace
  deploy/crds/operator.ibm.com_operandregistries_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_operandconfig_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.2/operand-deployment-lifecycle-manager.v1.2.2.clusterserviceversion.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.2/operator.ibm.com_operandregistries_crd.yaml
  deploy/role.yaml
  pkg/apis/operator/v1alpha1/operandregistry_types.go
  pkg/constant/constant.go
  pkg/controller/operandregistry/operandregistry_controller.go
  pkg/controller/operandrequest/reconcile_operand.go
  pkg/controller/operandrequest/reconcile_operator.go
Labels: approved, lgtm, size/L

#442 Move csv status checking out of get csv function
  pkg/controller/operandrequest/reconcile_operand.go
Labels: approved, lgtm, size/S

#446 Use multiErr when delete
  pkg/controller/operandrequest/operandrequest_controller.go
  pkg/controller/operandrequest/reconcile_operand.go
  pkg/controller/operandrequest/reconcile_operator.go
Labels: approved, lgtm, size/S

#447 Enhance default value to reduce k8s api call
  pkg/apis/operator/v1alpha1/operandbindinfo_types.go
  pkg/apis/operator/v1alpha1/operandconfig_types.go
  pkg/apis/operator/v1alpha1/operandregistry_types.go
  pkg/apis/operator/v1alpha1/operandrequest_types.go
  pkg/controller/operandbindinfo/operandbindinfo_controller.go
  pkg/controller/operandconfig/operandconfig_controller.go
  pkg/controller/operandregistry/operandregistry_controller.go
  pkg/controller/operandregistry/operandregistry_controller_test.go
  pkg/controller/operandrequest/config_status.go
  pkg/controller/operandrequest/operandrequest_controller.go
  pkg/controller/operandrequest/operandrequest_controller_test.go
  pkg/controller/operandrequest/reconcile_operand.go
  pkg/controller/operandrequest/reconcile_operator.go
Labels: approved, lgtm, size/L

#449 Add finalizers to operandRegistry and operandConfig
  pkg/apis/operator/v1alpha1/finalizer.go
  pkg/apis/operator/v1alpha1/operandbindinfo_types.go
  pkg/apis/operator/v1alpha1/operandconfig_types.go
  pkg/apis/operator/v1alpha1/operandregistry_types.go
  pkg/apis/operator/v1alpha1/operandrequest_types.go
  pkg/controller/operandconfig/operandconfig_controller.go
  pkg/controller/operandregistry/operandregistry_controller.go
  pkg/controller/operandrequest/operandrequest_controller.go
  pkg/controller/operandrequest/reconcile_operand.go
Labels: approved, lgtm, size/L
