Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2020-10, with the labels that each got.

#524 state the namespace in OperandRegistry
  api/v1alpha1/operandregistry_types.go
  docs/design/operand-deployment-lifecycle-manager.md
Labels: approved, lgtm, size/S

#526 disable leader election to avoid pod restarting
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/manager.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.4.0/operand-deployment-lifecycle-manager.v1.4.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#527 Use ibm-odlm as the package name
  Makefile
  api/v1alpha1/operandrequest_types.go
  bundle.Dockerfile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_operandbindinfos.yaml
  bundle/manifests/operator.ibm.com_operandconfigs.yaml
  bundle/manifests/operator.ibm.com_operandregistries.yaml
  bundle/manifests/operator.ibm.com_operandrequests.yaml
  bundle/metadata/annotations.yaml
  common/Makefile.common.mk
  common/scripts/install-opm.sh
  common/scripts/push-csv.sh
  config/crd/bases/operator.ibm.com_operandregistries.yaml
  config/crd/bases/operator.ibm.com_operandrequests.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.4.0/operand-deployment-lifecycle-manager.v1.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.4.0/operator.ibm.com_operandbindinfos_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.4.0/operator.ibm.com_operandconfigs_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.4.0/operator.ibm.com_operandregistries_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.4.0/operator.ibm.com_operandrequests_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/operand-deployment-lifecycle-manager.package.yaml
  docs/install/install-with-kind.md
  docs/install/install-with-ocp-3.11.md
  docs/install/install.md
Labels: approved, lgtm, size/L

#528 Update docs and comments
  api/v1alpha1/operandbindinfo_types.go
  api/v1alpha1/operandconfig_types.go
  api/v1alpha1/operandregistry_types.go
  api/v1alpha1/operandrequest_types.go
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_operandbindinfos.yaml
  bundle/manifests/operator.ibm.com_operandconfigs.yaml
  bundle/manifests/operator.ibm.com_operandregistries.yaml
  bundle/manifests/operator.ibm.com_operandrequests.yaml
  config/crd/bases/operator.ibm.com_operandbindinfos.yaml
  config/crd/bases/operator.ibm.com_operandconfigs.yaml
  config/crd/bases/operator.ibm.com_operandregistries.yaml
  config/crd/bases/operator.ibm.com_operandrequests.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  controllers/operandconfig_controller.go
  controllers/reconcile_operand.go
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.4.0/operand-deployment-lifecycle-manager.v1.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.4.0/operator.ibm.com_operandbindinfos_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.4.0/operator.ibm.com_operandconfigs_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.4.0/operator.ibm.com_operandregistries_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.4.0/operator.ibm.com_operandrequests_crd.yaml
  docs/design/operand-deployment-lifecycle-manager.md
  docs/dev/scorecard.md
  docs/images/create-operator-source.png
  docs/install/common-service-integration.md
  docs/install/install-with-kind.md
  docs/install/install-with-ocp-3.11.md
  docs/install/install.md
Labels: approved, lgtm, size/XXL

#530 update sa and namespace used in kustomize
  Makefile
  bundle/manifests/leader-election-role_rbac.authorization.k8s.io_v1_role.yaml
  bundle/manifests/leader-election-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
  bundle/manifests/manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/manager-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  bundle/manifests/operand-deployment-lifecycle-manager_rbac.authorization.k8s.io_v1_clusterrole.yaml
  config/manager/manager.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.4.0/operand-deployment-lifecycle-manager.v1.4.0.clusterserviceversion.yaml
  go.mod
Labels: approved, lgtm, size/L

#536 remove catalogsource check
  controllers/operandregistry_controller.go
Labels: approved, lgtm, size/M

#535 Operator is Running only after CSV is Succeeded
  controllers/reconcile_operand.go
Labels: approved, lgtm, size/XS

#537 Shrink permissions for ODLM
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/rbac/kustomization.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  controllers/constant/constant.go
  controllers/k8sutil/cache.go
  controllers/operandbindinfo_controller.go
  controllers/operandconfig_controller.go
  controllers/operandregistry_controller.go
  controllers/operandrequest_controller.go
  controllers/reconcile_operand.go
  controllers/util/get_env.go
  controllers/util/get_env_test.go
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.4.0/operand-deployment-lifecycle-manager.v1.4.0.clusterserviceversion.yaml
  go.mod
  go.sum
  main.go
Labels: approved, lgtm, size/XL

#538 fix the permission issue
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.4.0/operand-deployment-lifecycle-manager.v1.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
Labels: approved, lgtm, size/M

#539 update cluster role
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/rbac/role.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.4.0/operand-deployment-lifecycle-manager.v1.4.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/L
