Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2020-03, with the labels that each got.

#155 Add operandbindinginfo api and controller
  Makefile
  deploy/crds/operator.ibm.com_operandbindinfos_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_operandbindinfo_cr.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operator.ibm.com_operandbindinfos_crd.yaml
  deploy/role.yaml
  go.mod
  go.sum
  pkg/apis/operator/v1alpha1/operandbindinfo_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/add_operandbindinfo.go
  pkg/controller/operandbindinfo/operandbindinfo_controller.go
Labels: approved, lgtm, size/XL

#157 remove `required` section for dependency from onboard document
  docs/install/common-service-integration.md
Labels: approved, lgtm, size/S

#158 Add operand status in members and fix delete status issue
  common/config/.golangci.yml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
  pkg/apis/operator/v1alpha1/operandrequest_types.go
  pkg/controller/operandrequest/reconcile_operator.go
  pkg/controller/operandrequest/request_status.go
Labels: approved, lgtm, size/L

#160 add default namespace for OperandRegistry & OperandConfigs seed CRs
  deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#162 Integrate Exporter operator of IBM Monitoring stack
  deploy/crds/operator.ibm.com_v1alpha1_operandconfig_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#161 Support create operand request in another namespace
  Makefile
  pkg/apis/operator/v1alpha1/operandconfig_types.go
  pkg/apis/operator/v1alpha1/operandregistry_types.go
  pkg/controller/operandrequest/operandrequest_controller.go
  pkg/controller/operandrequest/request_status.go
Labels: approved, lgtm, size/S

#163 Update request api with ODLM new design
  deploy/crds/operator.ibm.com_operandrequests_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operator.ibm.com_operandrequests_crd.yaml
  pkg/apis/operator/v1alpha1/operandrequest_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/operandrequest/operandrequest_controller.go
  pkg/controller/operandrequest/operandrequest_controller_test.go
  pkg/controller/operandrequest/reconcile_operand.go
  pkg/controller/operandrequest/reconcile_operator.go
  pkg/controller/operandrequest/request_status.go
  test/helpers/helpers.go
  test/testsuits/operandrequest.go
Labels: approved, lgtm, size/XL

#166 integrate IBM Monitoring Prometheus Operator Extension
  deploy/crds/operator.ibm.com_v1alpha1_operandconfig_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#167 Restruct request api
  deploy/crds/operator.ibm.com_operandrequests_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operator.ibm.com_operandrequests_crd.yaml
  pkg/apis/operator/v1alpha1/operandrequest_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/operandrequest/operandrequest_controller.go
  pkg/controller/operandrequest/operandrequest_controller_test.go
  pkg/controller/operandrequest/reconcile_operand.go
  pkg/controller/operandrequest/reconcile_operator.go
  test/helpers/helpers.go
Labels: approved, lgtm, size/L

#168 Added upgrade section.
  docs/design/operand-deployment-lifecycle-manager.md
Labels: approved, lgtm, size/XS

#159 Add the cert-manager crs used to create the shared ca.
  deploy/crds/operator.ibm.com_v1alpha1_operandconfig_cr.yaml
Labels: approved, lgtm, size/XS

#169 Enhance OperandRegistry status to support one operator from OperandRequest
  deploy/crds/operator.ibm.com_operandregistries_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operator.ibm.com_operandregistries_crd.yaml
  pkg/apis/operator/v1alpha1/operandregistry_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/operandregistry/operandregistry_controller.go
  pkg/controller/operandrequest/operandrequest_controller.go
  pkg/controller/operandrequest/reconcile_operator.go
  pkg/controller/operandrequest/registry_status.go
Labels: approved, lgtm, size/L

#172 Link to design in README
  README.md
Labels: approved, lgtm, size/S

#173 Enhance push csv script to support update csv
  common/scripts/push-csv.sh
Labels: approved, lgtm, size/M

#174 Support delete specific operator
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
  go.mod
  go.sum
  pkg/apis/operator/v1alpha1/operandregistry_types.go
  pkg/controller/operandrequest/operandrequest_controller.go
  pkg/controller/operandrequest/reconcile_operand.go
  pkg/controller/operandrequest/reconcile_operator.go
Labels: approved, lgtm, size/L

#176 complete comments and remove registry list
  pkg/apis/operator/v1alpha1/operandconfig_types.go
  pkg/apis/operator/v1alpha1/operandregistry_types.go
  pkg/apis/operator/v1alpha1/operandrequest_types.go
  pkg/controller/operandregistry/operandregistry_controller.go
  pkg/controller/operandrequest/operandrequest_controller.go
Labels: approved, lgtm, size/L

#175 Update ubi version
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/XS

#177 Using Klog as log library
  cmd/manager/main.go
  deploy/crds/operator.ibm.com_operandconfigs_crd.yaml
  deploy/crds/operator.ibm.com_operandregistries_crd.yaml
  deploy/crds/operator.ibm.com_operandrequests_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operator.ibm.com_operandconfigs_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operator.ibm.com_operandregistries_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operator.ibm.com_operandrequests_crd.yaml
  deploy/operator.yaml
  go.mod
  pkg/controller/operandconfig/operandconfig_controller.go
  pkg/controller/operandregistry/operandregistry_controller.go
  pkg/controller/operandrequest/operandrequest_controller.go
  pkg/controller/operandrequest/reconcile_operand.go
  pkg/controller/operandrequest/reconcile_operator.go
  pkg/util/merge.go
  pkg/util/seed_cr.go
Labels: approved, lgtm, size/L

#179 Enhance request member status update
  cmd/manager/main.go
  pkg/apis/operator/v1alpha1/operandconfig_types.go
  pkg/controller/operandconfig/operandconfig_controller.go
  pkg/controller/operandregistry/operandregistry_controller.go
  pkg/controller/operandrequest/config_status.go
  pkg/controller/operandrequest/operandrequest_controller.go
  pkg/controller/operandrequest/operandrequest_controller_test.go
  pkg/controller/operandrequest/reconcile_operand.go
  pkg/controller/operandrequest/reconcile_operator.go
  pkg/controller/operandrequest/request_status.go
  pkg/util/merge.go
  pkg/util/seed_cr.go
Labels: approved, lgtm, size/L

#178 using digest to replace tag
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/XS

#181 Init config
  Makefile
  pkg/controller/operandconfig/operandconfig_controller.go
  pkg/controller/operandregistry/operandregistry_controller.go
  pkg/controller/operandrequest/config_status.go
  pkg/controller/operandrequest/reconcile_operand.go
  pkg/controller/operandrequest/reconcile_operator.go
Labels: approved, lgtm, size/M

#182 Add check logic before delete subscription
  pkg/controller/operandrequest/reconcile_operator.go
Labels: approved, lgtm, size/M

#183 Add label for health check
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#184 Update install doc
  docs/design/operand-deployment-lifecycle-manager.md
  docs/images/create-operand-request.png
  docs/images/create-operator-source.png
  docs/images/create-project.png
  docs/images/install-odlm-success.png
  docs/images/install-odlm.png
  docs/images/odlm-all-instances.png
  docs/images/operand-request-create-done.png
  docs/images/operand-request-detail.png
  docs/images/operator-list.png
  docs/images/operator-source-list.png
  docs/images/search-install-odlm-preview.png
  docs/images/search-odlm.png
  docs/install/common-service-integration.md
  docs/install/install.md
Labels: approved, lgtm, size/L

#186 Enhance OperandRequest status update
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/operandrequest/config_status.go
  pkg/controller/operandrequest/registry_status.go
  pkg/controller/operandrequest/request_status.go
Labels: approved, lgtm, size/S

#190 Add optional annotation and description
  deploy/crds/operator.ibm.com_operandregistries_crd.yaml
  deploy/crds/operator.ibm.com_operandrequests_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operator.ibm.com_operandregistries_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operator.ibm.com_operandrequests_crd.yaml
  pkg/apis/operator/v1alpha1/operandregistry_types.go
  pkg/apis/operator/v1alpha1/operandrequest_types.go
Labels: approved, lgtm, size/L

#192 add metering annotation
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#193 Add default handle logic for registryNamespace
  Makefile
  pkg/apis/operator/v1alpha1/operandrequest_types.go
  pkg/controller/operandrequest/operandrequest_controller.go
Labels: approved, lgtm, size/S

#195 adding navconfig to common-ui
  deploy/crds/operator.ibm.com_v1alpha1_operandconfig_cr.yaml
Labels: approved, lgtm, size/XS

#196 update helm squad operators
  deploy/crds/operator.ibm.com_v1alpha1_operandconfig_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#197 rename catalog-ui-operator
  deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
  docs/install/install-with-kind.md
  docs/install/install-with-ocp-3.11.md
  docs/install/install.md
Labels: approved, lgtm, size/S

#200 onboard grafana operator
  deploy/crds/operator.ibm.com_v1alpha1_operandconfig_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#201 Operandconfig delete
  deploy/crds/operator.ibm.com_v1alpha1_operandconfig_cr.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
  pkg/controller/operandrequest/config_status.go
  pkg/controller/operandrequest/operandrequest_controller.go
  pkg/controller/operandrequest/reconcile_operand.go
  pkg/util/lcFirst.go
Labels: approved, lgtm, size/L

#205 remove ibm-common-services namespace
  deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
  pkg/apis/operator/v1alpha1/operandconfig_types.go
Labels: approved, lgtm, size/S

#206 Enhance operandrequest member status
  pkg/controller/operandrequest/request_status.go
Labels: approved, lgtm, size/M

#207 Refactor operandConfig reconcile
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
  pkg/controller/operandrequest/config_status.go
  pkg/controller/operandrequest/reconcile_operand.go
  pkg/controller/operandrequest/reconcile_operator.go
  pkg/controller/operandrequest/request_status.go
Labels: approved, lgtm, size/L

#209 Adjust logs level
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/operandconfig/operandconfig_controller.go
  pkg/controller/operandregistry/operandregistry_controller.go
  pkg/controller/operandrequest/operandrequest_controller.go
  pkg/controller/operandrequest/reconcile_operator.go
  pkg/util/seed_cr.go
Labels: approved, lgtm, size/M

#210 remove unused management repo operator
  deploy/crds/operator.ibm.com_v1alpha1_operandconfig_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
  docs/install/install-with-kind.md
  docs/install/install-with-ocp-3.11.md
  docs/install/install.md
Labels: approved, lgtm, size/S

#211 Update the unit test to increase coverage
  pkg/controller/operandconfig/operandconfig_controller_test.go
  pkg/controller/operandregistry/operandregistry_controller.go
  pkg/controller/operandregistry/operandregistry_controller_test.go
  pkg/controller/operandrequest/operandrequest_controller_test.go
Labels: approved, lgtm, size/L

#215 Update finalizer check
  pkg/controller/operandrequest/operandrequest_controller.go
Labels: approved, lgtm, size/M

#213 get the config before update
  pkg/controller/operandrequest/config_status.go
Labels: approved, lgtm, size/M

#216 Support present operator for the operand request unit test
  Makefile
  pkg/controller/operandrequest/config_status.go
  pkg/controller/operandrequest/operandrequest_controller_test.go
  pkg/controller/operandrequest/request_status.go
Labels: approved, lgtm, size/L

#217 set default phase to operandRequest
  pkg/apis/operator/v1alpha1/operandrequest_types.go
Labels: approved, lgtm, size/XS

#220 Fix cluster phase display incorrect issue
  pkg/apis/operator/v1alpha1/operandconfig_types.go
  pkg/controller/operandrequest/config_status.go
  pkg/controller/operandrequest/operandrequest_controller.go
  pkg/controller/operandrequest/request_status.go
Labels: approved, lgtm, size/M

#221 Add phase to config and registry status
  deploy/crds/operator.ibm.com_operandconfigs_crd.yaml
  deploy/crds/operator.ibm.com_operandregistries_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operator.ibm.com_operandconfigs_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operator.ibm.com_operandregistries_crd.yaml
  pkg/apis/operator/v1alpha1/operandconfig_types.go
  pkg/apis/operator/v1alpha1/operandregistry_types.go
  pkg/apis/operator/v1alpha1/operandrequest_types.go
  pkg/controller/operandrequest/config_status.go
  pkg/controller/operandrequest/operandrequest_controller.go
Labels: approved, lgtm, size/L

#224 Update operandrequest member status with new phase
  pkg/apis/operator/v1alpha1/operandrequest_types.go
  pkg/controller/operandrequest/operandrequest_controller.go
  pkg/controller/operandrequest/operandrequest_controller_test.go
  pkg/controller/operandrequest/reconcile_operator.go
  pkg/controller/operandrequest/request_status.go
Labels: approved, lgtm, size/L

#225 Remove confuse init log
  Makefile
  pkg/apis/operator/v1alpha1/operandrequest_types.go
  pkg/controller/operandrequest/operandrequest_controller.go
Labels: approved, lgtm, size/M

#226 Enhance OperandRequest condition
  pkg/apis/operator/v1alpha1/operandrequest_types.go
  pkg/controller/operandrequest/reconcile_operator.go
Labels: approved, lgtm, size/M

#227 Uodate config status delete
  pkg/controller/operandrequest/config_status.go
  pkg/controller/operandrequest/reconcile_operand.go
  pkg/util/lcFirst.go
Labels: approved, lgtm, size/M

#228 Update status init for passing the rh certification
  pkg/apis/operator/v1alpha1/operandconfig_types.go
  pkg/apis/operator/v1alpha1/operandregistry_types.go
  pkg/controller/operandregistry/operandregistry_controller_test.go
  pkg/controller/operandrequest/config_status.go
  pkg/controller/operandrequest/registry_status.go
Labels: approved, lgtm, size/M

#231 Fix service status update issue
  pkg/apis/operator/v1alpha1/operandconfig_types.go
  pkg/controller/operandrequest/config_status.go
Labels: approved, lgtm, size/S

#232 Update unit test
  pkg/controller/operandconfig/operandconfig_controller_test.go
  pkg/controller/operandregistry/operandregistry_controller_test.go
  pkg/controller/operandrequest/operandrequest_controller_test.go
Labels: approved, lgtm, size/M

#233 Add image, go and license state on README
  README.md
Labels: approved, lgtm, size/XS

#219 logging operator
  deploy/crds/operator.ibm.com_v1alpha1_operandconfig_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#234 Enhance unit test
  README.md
  common/scripts/codecov.sh
  pkg/apis/operator/v1alpha1/operandconfig_types.go
  pkg/apis/operator/v1alpha1/operandregistry_types.go
  pkg/controller/operandconfig/operandconfig_controller_test.go
  pkg/controller/operandregistry/operandregistry_controller_test.go
  pkg/controller/operandrequest/config_status.go
  pkg/controller/operandrequest/operandrequest_controller_test.go
  pkg/controller/operandrequest/request_status.go
Labels: approved, lgtm, size/M

#235 Update OperandRequest CR
  deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#239 Update odlm csv description
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
  docs/design/operand-deployment-lifecycle-manager.md
Labels: approved, lgtm, size/M

#237 Enable common ui
  deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#238 Move member status update after waiting for subscriptions ready
  pkg/controller/operandrequest/operandrequest_controller.go
  pkg/controller/operandrequest/operandrequest_controller_test.go
  pkg/controller/operandrequest/reconcile_operator.go
  pkg/controller/operandrequest/request_status.go
Labels: approved, lgtm, size/S

#243 remove codecov upload token from source
  common/scripts/codecov.sh
Labels: approved, lgtm, size/XS

#240 fix typo in design doc
  docs/design/operand-deployment-lifecycle-manager.md
Labels: approved, lgtm, size/XS

#244 Enhance e2e test
  common/config/.golangci.yml
  go.mod
  go.sum
  pkg/controller/operandrequest/operandrequest_controller_test.go
Labels: approved, lgtm, size/L

#242 support real multiarch build.
  Makefile
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  common/scripts/gobuild.sh
  common/scripts/multiarch_image.sh
Labels: approved, lgtm, size/L

#245 update retry times and interval for multiarch image build.
  Makefile
Labels: approved, lgtm, size/XS

#247 onboard prometheus operator as crd dependency is deprecated by ODLM
  deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#248 Add introduction for CRD short names
  README.md
  docs/design/operand-deployment-lifecycle-manager.md
Labels: approved, lgtm, size/S

#249 Fix delete operand request issue
  pkg/controller/operandrequest/reconcile_operand.go
Labels: approved, lgtm, size/XS

#250 Update operator list
  docs/install/install.md
Labels: approved, lgtm, size/XS

#251 update channel for monitoring operators
  deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#252 Change channel of ingress operator to stable
  deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#255 change channel of auditlogging operator to stable
  deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#256 Update mongo channel
  deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#258 fix image version.
  Makefile
  common/scripts/multiarch_image.sh
Labels: approved, lgtm, size/XS

#259 Remove prometheus-operator from CRs and CSV
  deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#254 Update ODLM version to 1.1.0
  .osdk-scorecard.yaml
  Makefile
  common/scripts/multiarch_image.sh
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operand-deployment-lifecycle-manager.v1.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operator.ibm.com_operandconfigs_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operator.ibm.com_operandregistries_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operator.ibm.com_operandrequests_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/operand-deployment-lifecycle-manager.package.yaml
  deploy/operator.yaml
  docs/install/common-service-integration.md
  version/version.go
Labels: approved, lgtm, size/XL

#257 change metering channel to stable-v3
  deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#262 Update new csv
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operand-deployment-lifecycle-manager.v1.1.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/L

#260 Remove prometheus-operator from list
  docs/install/install.md
Labels: approved, lgtm, size/XS

#266 update healthcheck channel
  deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operand-deployment-lifecycle-manager.v1.1.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#263 Update csv maturity to stable
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operand-deployment-lifecycle-manager.v1.1.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#264 Use latest tag now
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operand-deployment-lifecycle-manager.v1.1.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#261 changed logging channel
  deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
Labels: approved, lgtm, size/XS

#265 update channel for helm operators
  deploy/crds/operator.ibm.com_v1alpha1_operandconfig_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operand-deployment-lifecycle-manager.v1.1.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#267 Update logging csv channel
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operand-deployment-lifecycle-manager.v1.1.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#268 update licensing channel
  deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operand-deployment-lifecycle-manager.v1.1.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#269 change metering channel to stable-v1
  deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operand-deployment-lifecycle-manager.v1.1.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#270 update cert-manager channel
  deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operand-deployment-lifecycle-manager.v1.1.0.clusterserviceversion.yaml
Labels: approved, size/XS

#271 Update iam and commonui channel
  deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operand-deployment-lifecycle-manager.v1.1.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#272 remove 0.0.1 csv
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operator.ibm.com_operandconfigs_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operator.ibm.com_operandregistries_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operator.ibm.com_operandrequests_crd.yaml
Labels: approved, lgtm, size/XXL

#274 Update readme to follow common service template
  README.md
  docs/design/operand-deployment-lifecycle-manager.md
Labels: approved, lgtm, size/M

#275 Add event when operandregistry not found
  pkg/controller/operandrequest/reconcile_operator.go
Labels: approved, lgtm, size/XS

#277 Update operand-deployment-lifecycle-manager.v1.1.0.clusterservicevers…
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operand-deployment-lifecycle-manager.v1.1.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#278 update ODLM operator image version
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operand-deployment-lifecycle-manager.v1.1.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#229 RH certify
  .gitignore
  common/Makefile.common.mk
  common/scripts/create_bundle.sh
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operand-deployment-lifecycle-manager.v1.1.0.clusterserviceversion.yaml
  pkg/apis/operator/v1alpha1/operandregistry_types.go
Labels: approved, lgtm, size/L
