Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2020-04, with the labels that each got.

#286 Add resource annotation and enable all common services
  deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operand-deployment-lifecycle-manager.v1.1.0.clusterserviceversion.yaml
  pkg/apis/operator/v1alpha1/operandconfig_types.go
  pkg/apis/operator/v1alpha1/operandregistry_types.go
  pkg/apis/operator/v1alpha1/operandrequest_types.go
Labels: approved, lgtm, size/L

#288 Update install document
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operand-deployment-lifecycle-manager.v1.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operand-deployment-lifecycle-manager.v1.2.0.clusterserviceversion.yaml
  docs/design/how-to-update-operandconfig.md
  docs/design/how-to-update-operandregistry.md
  docs/images/create-operator-source.png
  docs/install/install.md
Labels: approved, lgtm, size/L

#292 Add examples for OperandRequest and OperandRegistry update document
  docs/design/how-to-update-operandconfig.md
  docs/design/how-to-update-operandregistry.md
  docs/images/before-update.png
  docs/images/etcd-channel-after.png
  docs/images/etcd-channel-before.png
  docs/images/etcd-cluster-before.png
  docs/images/etcd-cluster-example-after.png
  docs/images/etcd-cluster-example-before.png
  pkg/controller/.DS_Store
Labels: approved, lgtm, size/L

#291 Add Ready status for condition status
  pkg/apis/operator/v1alpha1/operandrequest_types.go
  pkg/controller/operandrequest/operandrequest_controller.go
Labels: approved, lgtm, size/M

#296 Add OperandBindInfo
  Makefile
  deploy/crds/operator.ibm.com_operandbindinfos_crd.yaml
  deploy/crds/operator.ibm.com_operandrequests_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operand-deployment-lifecycle-manager.v1.2.0.clusterserviceversion.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operator.ibm.com_operandbindinfos_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operator.ibm.com_operandrequests_crd.yaml
  deploy/role.yaml
  pkg/apis/operator/v1alpha1/operandbindinfo_types.go
  pkg/apis/operator/v1alpha1/operandrequest_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/add_operandbindinfo.go
  pkg/controller/operandbindinfo/bindInfo_status.go
  pkg/controller/operandbindinfo/operandbindinfo_controller.go
  pkg/controller/operandrequest/operandrequest_controller.go
  pkg/controller/operandrequest/operandrequest_controller_test.go
  pkg/controller/operandrequest/reconcile_operand.go
  pkg/util/multi_errors.go
Labels: approved, lgtm, size/XL

#298 Add unit test for OperandBindInfo
  common/config/.golangci.yml
  pkg/controller/operandbindinfo/operandbindinfo_controller.go
  pkg/controller/operandbindinfo/operandbindinfo_controller_test.go
Labels: approved, lgtm, size/L

#297 Add OperandBindInfo into document and README
  README.md
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operand-deployment-lifecycle-manager.v1.2.0.clusterserviceversion.yaml
  docs/design/operand-deployment-lifecycle-manager.md
Labels: approved, lgtm, size/M

#299 Set csv as the owner of the operandrequest instance
  pkg/controller/operandrequest/reconcile_operand.go
Labels: approved, lgtm, size/M

#302 Move some methods to api
  pkg/apis/operator/v1alpha1/operandconfig_types.go
  pkg/apis/operator/v1alpha1/operandregistry_types.go
  pkg/controller/operandrequest/operandrequest_controller.go
  pkg/controller/operandrequest/reconcile_operand.go
  pkg/controller/operandrequest/reconcile_operator.go
Labels: approved, lgtm, size/M

#304 Enhance bindinfo obtain namespace logic
  pkg/controller/operandbindinfo/operandbindinfo_controller.go
Labels: approved, lgtm, size/S

#306 Add print column for 4 crds
  deploy/crds/operator.ibm.com_operandbindinfos_crd.yaml
  deploy/crds/operator.ibm.com_operandconfigs_crd.yaml
  deploy/crds/operator.ibm.com_operandregistries_crd.yaml
  deploy/crds/operator.ibm.com_operandrequests_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operator.ibm.com_operandbindinfos_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operator.ibm.com_operandconfigs_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operator.ibm.com_operandregistries_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operator.ibm.com_operandrequests_crd.yaml
  pkg/apis/operator/v1alpha1/operandbindinfo_types.go
  pkg/apis/operator/v1alpha1/operandconfig_types.go
  pkg/apis/operator/v1alpha1/operandregistry_types.go
  pkg/apis/operator/v1alpha1/operandrequest_types.go
Labels: approved, lgtm, size/L

#307 watch secret and configmap
  go.mod
  go.sum
  pkg/controller/operandbindinfo/operandbindinfo_controller.go
Labels: approved, lgtm, size/M

#308 Enhance uninstall
  pkg/controller/operandrequest/reconcile_operand.go
Labels: approved, lgtm, size/M

#309 Updated odlm arch by adding opbi
  docs/images/odlm-arch.png
Labels: approved, lgtm, size/XS

#311 Update layout for doc
  docs/user/how-to-update-operandconfig.md
  docs/user/how-to-update-operandregistry.md
Labels: approved, lgtm, size/XS

#313 Restruct the bindinfo controller
  pkg/controller/operandbindinfo/operandbindinfo_controller.go
Labels: approved, lgtm, size/L

#315 Skip operand update when specs are same
  pkg/controller/operandrequest/reconcile_operand.go
Labels: approved, lgtm, size/XS

#316 Add doc about how to use bindinfo
  docs/design/operand-deployment-lifecycle-manager.md
  docs/user/how-to-use-operandBindInfo.md
Labels: approved, lgtm, size/M

#319 bindinfo mapping
  deploy/crds/operator.ibm.com_operandrequests_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operator.ibm.com_operandrequests_crd.yaml
  pkg/apis/operator/v1alpha1/operandrequest_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/operandbindinfo/operandbindinfo_controller.go
  pkg/controller/operandbindinfo/operandbindinfo_controller_test.go
Labels: approved, lgtm, size/L

#320 Enhance registry controller to trigger request reconcile
  pkg/apis/operator/v1alpha1/operandbindinfo_types.go
  pkg/apis/operator/v1alpha1/operandrequest_types.go
  pkg/controller/operandconfig/operandconfig_controller.go
  pkg/controller/operandconfig/operandconfig_controller_test.go
  pkg/controller/operandregistry/operandregistry_controller.go
  pkg/controller/operandregistry/operandregistry_controller_test.go
  pkg/controller/operandrequest/operandrequest_controller.go
Labels: approved, lgtm, size/L

#324 Add label into Operandbindinfo instance
  deploy/crds/operator.ibm.com_operandbindinfos_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operator.ibm.com_operandbindinfos_crd.yaml
  pkg/apis/operator/v1alpha1/operandbindinfo_types.go
  pkg/apis/operator/v1alpha1/operandrequest_types.go
  pkg/controller/operandbindinfo/operandbindinfo_controller.go
  pkg/controller/operandregistry/operandregistry_controller.go
Labels: approved, lgtm, size/M

#325 Use latest image tag when development phase
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#327 Remove useless code from main.go
  cmd/manager/main.go
Labels: approved, lgtm, size/M

#328 Update image version in csv
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operand-deployment-lifecycle-manager.v1.2.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#330 Fix add label issue
  pkg/apis/operator/v1alpha1/operandbindinfo_types.go
  pkg/apis/operator/v1alpha1/operandrequest_types.go
Labels: approved, lgtm, size/XS

#332 Fix copy config map issue
  pkg/controller/operandbindinfo/operandbindinfo_controller.go
Labels: approved, lgtm, size/M

#334 Enhance unit test for 2Q
  pkg/controller/operandbindinfo/operandbindinfo_controller_test.go
  pkg/controller/operandconfig/operandconfig_controller_test.go
  pkg/controller/operandregistry/operandregistry_controller_test.go
  pkg/controller/operandrequest/operandrequest_controller_test.go
Labels: approved, lgtm, size/XL

#336 Add prefix for the copied cm and secret
  pkg/controller/operandbindinfo/operandbindinfo_controller.go
Labels: approved, lgtm, size/S

#339 Enhance operandConfig reconcile
  deploy/crds/operator.ibm.com_v1alpha1_operandconfig_cr.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operand-deployment-lifecycle-manager.v1.2.0.clusterserviceversion.yaml
  pkg/controller/operandbindinfo/operandbindinfo_controller.go
  pkg/controller/operandconfig/operandconfig_controller.go
  pkg/controller/operandrequest/reconcile_operand.go
  pkg/controller/operandrequest/reconcile_operator.go
Labels: approved, lgtm, size/L

#341 remove navconfiguration: {}
  common/scripts/multiarch_image.sh
  deploy/crds/operator.ibm.com_v1alpha1_operandconfig_cr.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operand-deployment-lifecycle-manager.v1.1.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#342 Add bindinfo e2e test
  Makefile
  test/config/constants.go
  test/e2e/odlm_test.go
  test/helpers/helpers.go
  test/testgroups/operandbindinfo_group.go
  test/testgroups/operandrequest_group.go
Labels: approved, lgtm, size/L

#345 Add more case assert for e2e
  test/config/constants.go
  test/e2e/odlm_test.go
  test/helpers/helpers.go
  test/testgroups/operandbindinfo_group.go
  test/testgroups/operandconfig_group.go
  test/testgroups/operandregistry_group.go
  test/testgroups/operandrequest_group.go
Labels: approved, lgtm, size/XL

#347 Fix OperandBindInfo init stauts issue
  pkg/apis/operator/v1alpha1/operandbindinfo_types.go
Labels: approved, lgtm, size/XS

#349 Skip reconcile bindinfo when requestNamespaces less than 2
  pkg/controller/operandbindinfo/operandbindinfo_controller.go
  pkg/controller/operandbindinfo/operandbindinfo_controller_test.go
Labels: approved, lgtm, size/XS

#354 Requeue for bindinfo
  pkg/apis/operator/v1alpha1/operandbindinfo_types.go
  pkg/controller/operandbindinfo/operandbindinfo_controller.go
  pkg/controller/operandrequest/operandrequest_controller.go
Labels: approved, lgtm, size/M

#356 Refactor bindings field in the OperandRequest and OperandBindInfo
  deploy/crds/operator.ibm.com_operandbindinfos_crd.yaml
  deploy/crds/operator.ibm.com_operandrequests_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operator.ibm.com_operandbindinfos_crd.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operator.ibm.com_operandrequests_crd.yaml
  pkg/apis/operator/v1alpha1/operandbindinfo_types.go
  pkg/apis/operator/v1alpha1/operandrequest_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/operandbindinfo/operandbindinfo_controller.go
  pkg/controller/operandbindinfo/operandbindinfo_controller_test.go
  pkg/controller/operandregistry/operandregistry_controller_test.go
  test/helpers/helpers.go
  test/testgroups/operandbindinfo_group.go
Labels: approved, lgtm, size/L

#353 append label and remove the label for the same function
  pkg/apis/operator/v1alpha1/operandbindinfo_types.go
  pkg/apis/operator/v1alpha1/operandrequest_types.go
Labels: approved, lgtm, size/S

#357 Fix e2e test issue
  Makefile
  cmd/manager/main.go
  deploy/role_binding.yaml
  test/config/constants.go
  test/helpers/helpers.go
  test/testgroups/operandbindinfo_group.go
  test/testgroups/operandconfig_group.go
  test/testgroups/operandregistry_group.go
  test/testgroups/operandrequest_group.go
Labels: approved, lgtm, size/L

#358 Update end to end test
  docs/dev/e2e.md
  test/helpers/helpers.go
  test/testgroups/operandbindinfo_group.go
  test/testgroups/operandrequest_group.go
Labels: approved, lgtm, size/M

#362 Removing platform header from config
  deploy/crds/operator.ibm.com_v1alpha1_operandconfig_cr.yaml
Labels: approved, lgtm, size/XS

#363 Revert 349 for Cloud Pak use case
  README.md
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operand-deployment-lifecycle-manager.v1.2.0.clusterserviceversion.yaml
  pkg/controller/operandbindinfo/operandbindinfo_controller.go
  pkg/controller/operandbindinfo/operandbindinfo_controller_test.go
Labels: approved, lgtm, size/S

#301 Remove default created operandconfig and operandregistry
  Makefile
  build/Dockerfile
  go.mod
  pkg/controller/operandconfig/operandconfig_controller.go
  pkg/controller/operandregistry/operandregistry_controller.go
  pkg/util/seed_cr.go
Labels: approved, lgtm, priority/p1, size/L

#364 Remove alm-example from csv
  deploy/crds/operator.ibm.com_v1alpha1_operandconfig_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operand-deployment-lifecycle-manager.v1.2.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XL

#365 Update csv describe with jenkins example
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operand-deployment-lifecycle-manager.v1.2.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/L

#340 Add a check for operator scope
  pkg/apis/operator/v1alpha1/operandrequest_types.go
  pkg/controller/operandrequest/reconcile_operator.go
Labels: approved, lgtm, size/S

#367 Support multi secret and configmap binding
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operand-deployment-lifecycle-manager.v1.2.0.clusterserviceversion.yaml
  pkg/controller/operandbindinfo/operandbindinfo_controller.go
Labels: approved, lgtm, size/L
