Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2020-08, with the labels that each got.

#485 config docker before push the images
  Makefile
Labels: approved, lgtm, size/XS

#486 config docker before pushing images
  Makefile
Labels: approved, lgtm, size/XS

#487 seperator bundle and operator image pushing
  Makefile
  common/Makefile.common.mk
  common/scripts/artifactory_config_docker.sh
  common/scripts/quay_config_docker.sh
Labels: approved, lgtm, size/M

#484 controller doesn't return error when the installplan is failed
  controllers/common/fetch.go
Labels: approved, lgtm, size/XS

#491 Update OperandBindinfo controller unit test
  Makefile
  controllers/operandbindinfo_controller_test.go
  controllers/suite_test.go
Labels: approved, lgtm, size/L

#492 Remove productVersion metering annotations
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manager/manager.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.3.0/operand-deployment-lifecycle-manager.v1.3.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#493 use ubi as base image for ODLM
  Dockerfile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.3.0/operand-deployment-lifecycle-manager.v1.3.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#494 don't change the operator deployment name for odlm
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manager/manager.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.4/operand-deployment-lifecycle-manager.v1.2.4.clusterserviceversion.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.3.0/operand-deployment-lifecycle-manager.v1.3.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#495 Fix build multi arch image issue
  Makefile
  common/scripts/multiarch_image.sh
Labels: approved, lgtm, size/M

#496 Remove the hardcoded goarch
  Dockerfile
  Makefile
Labels: approved, lgtm, size/XS

#499 Update makefile and bundle manifest template
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/default/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/rbac/role.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.3.0/operand-deployment-lifecycle-manager.v1.3.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#500 Update go version to 1.14.7
  Dockerfile
Labels: approved, lgtm, size/XS

#501 Add displayname for OperandConfig
  api/v1alpha1/operandconfig_types.go
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.3.0/operand-deployment-lifecycle-manager.v1.3.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#497 catch error logs from the reconciliation failure
  controllers/operandrequest_controller.go
  controllers/reconcile_operand.go
  controllers/reconcile_operator.go
Labels: approved, lgtm, size/S

#498 Add unit test for controllers
  Makefile
  api/v1alpha1/operandregistry_types.go
  api/v1alpha1/operandrequest_types.go
  controllers/operandbindinfo_controller.go
  controllers/operandbindinfo_controller_test.go
  controllers/operandconfig_controller.go
  controllers/operandconfig_controller_test.go
  controllers/operandregistry_controller.go
  controllers/operandregistry_controller_test.go
  controllers/operandrequest_controller.go
  controllers/operandrequest_controller_test.go
  controllers/suite_test.go
Labels: approved, lgtm, size/XXL

#502 add license
  Dockerfile
Labels: approved, lgtm, size/XS
