Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2021-01, with the labels that each got.

#585 grant permission for ODLM CRDs
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/rbac/role.yaml
Labels: approved, lgtm, size/XS

#588 update copyright for 2021
  Makefile
  api/v1alpha1/finalizer.go
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/operandbindinfo_types.go
  api/v1alpha1/operandconfig_types.go
  api/v1alpha1/operandregistry_types.go
  api/v1alpha1/operandrequest_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  common/Makefile.common.mk
  common/scripts/.githooks/make_lint-all.sh
  common/scripts/.githooks/pre-commit
  common/scripts/artifactory_config_docker.sh
  common/scripts/codecov.sh
  common/scripts/create_bundle.sh
  common/scripts/gobuild.sh
  common/scripts/install-kind.sh
  common/scripts/install-kubebuilder.sh
  common/scripts/install-olm.sh
  common/scripts/install-operator-sdk.sh
  common/scripts/install-opm.sh
  common/scripts/lint_copyright_banner.sh
  common/scripts/lint_go.sh
  common/scripts/multiarch_image.sh
  common/scripts/push-csv.sh
  common/scripts/quay_config_docker.sh
  controllers/common/fetch.go
  controllers/constant/constant.go
  controllers/k8sutil/cache.go
  controllers/operandbindinfo/operandbindinfo_controller.go
  controllers/operandbindinfo/operandbindinfo_controller_test.go
  controllers/operandbindinfo/operandbindinfo_suite_test.go
  controllers/operandconfig/operandconfig_controller.go
  controllers/operandconfig/operandconfig_controller_test.go
  controllers/operandconfig/operandconfig_suite_test.go
  controllers/operandregistry/operandregistry_controller.go
  controllers/operandregistry/operandregistry_controller_test.go
  controllers/operandregistry/operandregistry_suite_test.go
  controllers/operandrequest/operandrequest_controller.go
  controllers/operandrequest/operandrequest_controller_suit_test.go
  controllers/operandrequest/operandrequest_controller_test.go
  controllers/operandrequest/reconcile_operand.go
  controllers/operandrequest/reconcile_operator.go
  controllers/testutil/test_data.go
  controllers/testutil/test_util.go
  controllers/util/merge.go
  controllers/util/merge_test.go
  controllers/util/multi_errors.go
  controllers/util/multi_errors_test.go
  controllers/util/util.go
  controllers/util/util_suite_test.go
  controllers/util/util_test.go
  hack/boilerplate.go.txt
  main.go
  test/e2e/constants.go
  test/e2e/e2e_suite_test.go
  test/e2e/helpers_test.go
  test/e2e/odlm_test.go
  test/e2e/utils_test.go
  version/version.go
Labels: approved, lgtm, size/L

#589 added bitscuit to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#590 Move fetch method to manager.go
  Makefile
  controllers/deploy/manager.go
  controllers/operandbindinfo/operandbindinfo_controller.go
  controllers/operandbindinfo/operandbindinfo_suite_test.go
  controllers/operandconfig/operandconfig_controller.go
  controllers/operandconfig/operandconfig_suite_test.go
  controllers/operandregistry/operandregistry_controller.go
  controllers/operandregistry/operandregistry_suite_test.go
  controllers/operandrequest/operandrequest_controller.go
  controllers/operandrequest/operandrequest_controller_suit_test.go
  controllers/operandrequest/reconcile_operand.go
  controllers/operandrequest/reconcile_operator.go
  main.go
Labels: approved, lgtm, size/L

#591 Avoid to use api reader to cause extra api call.
  controllers/deploy/manager.go
  controllers/operandbindinfo/operandbindinfo_controller.go
  controllers/operandconfig/operandconfig_controller.go
  controllers/operandrequest/operandrequest_controller.go
  controllers/operandrequest/reconcile_operand.go
  controllers/operandrequest/reconcile_operator.go
Labels: approved, lgtm, size/M

#592 Using level 1 in the runtime, using level 2 for debugging
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: approved, lgtm, size/XS

#593 Support package catalog and approvall updating in the subscription
  api/v1alpha1/operandregistry_types.go
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  controllers/operandrequest/reconcile_operator.go
Labels: approved, lgtm, size/S

#594 fix vulnerability issue CVE-2021-3121
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#595 switch 1.5 to v3 channel
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#596 Refactor some functions
  Makefile
  common/Makefile.common.mk
  controllers/constant/constant.go
  controllers/k8sutil/cache.go
  controllers/operandbindinfo/operandbindinfo_controller.go
  controllers/operandbindinfo/operandbindinfo_suite_test.go
  controllers/operandconfig/operandconfig_controller.go
  controllers/operandconfig/operandconfig_suite_test.go
  controllers/operandregistry/operandregistry_controller.go
  controllers/operandregistry/operandregistry_suite_test.go
  controllers/operandrequest/operandrequest_controller.go
  controllers/operandrequest/operandrequest_suit_test.go
  controllers/operandrequest/reconcile_operand.go
  controllers/operandrequest/reconcile_operator.go
  controllers/operator/manager.go
  controllers/util/multi_errors.go
  controllers/util/multi_errors_test.go
  go.mod
  main.go
Labels: approved, lgtm, size/XXL

#597 Porting protobuf fix to EUS
  go.mod
  go.sum
Labels: lgtm, size/M

#598 update jeknis source
  common/Makefile.common.mk
Labels: approved, lgtm, size/XS

#599 fix: Remove the rbac files from bundle folder
  bundle/manifests/operand-deployment-lifecycle-manager_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  bundle/manifests/operand-deployment-lifecycle-manager_v1_serviceaccount.yaml
Labels: approved, lgtm, size/S
