Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2021-02, with the labels that each got.

#602 fix: fix namespace check logic
  controllers/operandrequest/reconcile_operator.go
Labels: approved, lgtm, size/XS

#603 updated go to version 1.15.7 to fix CVE-2021-3114 and CVE-2021-3115
  Dockerfile
  go.mod
Labels: approved, lgtm, size/XS

#606 added bitscuit and Daniel-Fan to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#604 feat: operandregistry status update
  controllers/operandregistry/operandregistry_controller.go
  controllers/operandrequest/operandrequest_controller.go
  controllers/operandrequest/reconcile_operator.go
  controllers/operator/manager.go
Labels: approved, lgtm, size/M

#608 feat: Support `protected` prefix in bindinfo.
  controllers/operandbindinfo/operandbindinfo_controller.go
  controllers/operandbindinfo/operandbindinfo_controller_test.go
  controllers/testutil/test_util.go
  docs/design/operand-deployment-lifecycle-manager.md
Labels: approved, lgtm, size/L

#610 handle that not found operator in operandregistry
  controllers/operandbindinfo/operandbindinfo_controller.go
Labels: approved, lgtm, size/XS

#612 replace deprecated api
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operand-deployment-lifecycle-manager.v1.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operand-deployment-lifecycle-manager.v1.2.0.clusterserviceversion.yaml
  deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.1/operand-deployment-lifecycle-manager.v1.2.1.clusterserviceversion.yaml
  docs/user/how-to-update-operandregistry.md
  docs/user/how-to-use-operandBindInfo.md
Labels: approved, lgtm, size/S

#613 feat: add annotation to indicate if the operandregistry is found
  controllers/constant/constant.go
  controllers/operandrequest/reconcile_operator.go
Labels: approved, lgtm, size/S

#614 feat: When OperandRequest is updated, bindinfo controller should be t…
  controllers/operandbindinfo/operandbindinfo_controller.go
Labels: approved, lgtm, size/M

#617 adjust log level
  controllers/operandconfig/operandconfig_controller.go
  controllers/operandrequest/operandrequest_controller.go
  controllers/operandrequest/reconcile_operand.go
  controllers/operandrequest/reconcile_operator.go
Labels: approved, lgtm, size/S

#618 check if the service exists in the opcon, then update the status
  controllers/operandconfig_controller.go
Labels: approved, lgtm, size/XS

#619 fix: Avoid having the permission to use any scc
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/rbac/role.yaml
Labels: approved, lgtm, size/S

#611 handle that not found operator in operandregistry in release-1.4
  controllers/operandbindinfo_controller.go
Labels: approved, lgtm, size/XS
