Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2021-03, with the labels that each got.

#629 bump operator version to 1.6.0
  CONTRIBUTING.md
  Makefile
  OWNERS
  SECURITY_CONTACTS
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/M

#630 docs: Add a document to compare OLM and ODLM
  docs/design/comparison-to-olm.md
Labels: approved, lgtm, size/M

#631 Update comparison-to-olm.md
  docs/design/comparison-to-olm.md
Labels: approved, lgtm, size/S

#626 feat: Delete resources in parallel
  controllers/operandrequest/reconcile_operand.go
  controllers/operandrequest/reconcile_operator.go
Labels: approved, lgtm, size/M

#634 Generalize the dependency examples.
  docs/design/comparison-to-olm.md
Labels: approved, lgtm, size/XS

#633 docs: Update documents to make them work with the latest version
  Makefile
  docs/design/operand-deployment-lifecycle-manager.md
  docs/dev/development.md
  docs/dev/e2e.md
  docs/dev/scorecard.md
  docs/install/install-with-kind.md
  docs/install/install-with-ocp-3.11.md
  docs/install/install.md
Labels: approved, lgtm, size/L

#641 updated golang and ubi images to 1.15.10 and 8.3-291, respectively
  Dockerfile
Labels: approved, lgtm, size/XS

#609 feat: Create namespacescope controller
  Makefile
  common/Makefile.common.mk
  controllers/namespacescope/namespacescope_controler_test.go
  controllers/namespacescope/namespacescope_controller.go
  controllers/namespacescope/namespacescope_suite_test.go
  controllers/operandrequest/operandrequest_controller.go
  controllers/operandrequest/reconcile_operator.go
  controllers/operator/manager.go
  controllers/testutil/test_util.go
  main.go
Labels: approved, cherry-pick release 3.6, lgtm, size/XL

#639 Support multiOpeReg with same Operator
  controllers/operandrequest/operandrequest_controller_test.go
  controllers/operandrequest/operandrequest_suite_test.go
  controllers/operandrequest/reconcile_operator.go
  controllers/testutil/test_util.go
Labels: approved, lgtm, size/L

#642 create namespace scope controller
  Makefile
  common/Makefile.common.mk
  controllers/common/fetch.go
  controllers/namespacescope_controller.go
  controllers/namespacescope_controller_test.go
  controllers/operandrequest_controller.go
  controllers/suite_test.go
  controllers/testutil/test_data.go
  go.mod
  go.sum
  main.go
Labels: approved, lgtm, size/XL
