Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2021-06, with the labels that each got.

#681 fix: add more checkings in alm-example for unexpected panic
  controllers/operandconfig/operandconfig_controller.go
  controllers/operandrequest/reconcile_operand.go
Labels: approved, lgtm, size/S

#682 remove debug logs
  controllers/operandrequest/reconcile_operand.go
Labels: approved, lgtm, size/XS

#683 build: enable Dependabot to upgrade base images
  .github/dependabot.yml
  Dockerfile
Labels: approved, lgtm, size/XS

#687 Updated the OperandBindInfo sample
  docs/user/how-to-use-operandBindInfo.md
Labels: approved, lgtm, size/S

#691 bump operator version to 1.6.1
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#692 chore: bump k8s to 1.20
  controllers/k8sutil/cache.go
  controllers/namespacescope/namespacescope_controller.go
  controllers/namespacescope/namespacescope_suite_test.go
  controllers/operandbindinfo/operandbindinfo_controller.go
  controllers/operandbindinfo/operandbindinfo_suite_test.go
  controllers/operandconfig/operandconfig_controller.go
  controllers/operandconfig/operandconfig_suite_test.go
  controllers/operandregistry/operandregistry_controller.go
  controllers/operandregistry/operandregistry_suite_test.go
  controllers/operandrequest/operandrequest_controller.go
  controllers/operandrequest/operandrequest_suite_test.go
  go.mod
  go.sum
  test/e2e/helpers_test.go
  test/e2e/utils_test.go
Labels: approved, lgtm, size/XL

#693 fix requestNamespaces for iam/management-ingress bindinfo
  controllers/operandbindinfo/operandbindinfo_controller.go
Labels: approved, lgtm, size/XS

#695 bump operator version to 2.0.0 for future release in master branch
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#696 add minKubeVersion and update operator-sdk
  PROJECT
  bundle.Dockerfile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_operandbindinfos.yaml
  bundle/manifests/operator.ibm.com_operandconfigs.yaml
  bundle/manifests/operator.ibm.com_operandregistries.yaml
  bundle/manifests/operator.ibm.com_operandrequests.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/operator.ibm.com_operandbindinfos.yaml
  config/crd/bases/operator.ibm.com_operandconfigs.yaml
  config/crd/bases/operator.ibm.com_operandregistries.yaml
  config/crd/bases/operator.ibm.com_operandrequests.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
Labels: approved, lgtm, size/XL

#697 add minKubeVersion and update operator-sdk (#696)
  PROJECT
  bundle.Dockerfile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_operandbindinfos.yaml
  bundle/manifests/operator.ibm.com_operandconfigs.yaml
  bundle/manifests/operator.ibm.com_operandregistries.yaml
  bundle/manifests/operator.ibm.com_operandrequests.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/operator.ibm.com_operandbindinfos.yaml
  config/crd/bases/operator.ibm.com_operandconfigs.yaml
  config/crd/bases/operator.ibm.com_operandregistries.yaml
  config/crd/bases/operator.ibm.com_operandrequests.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
Labels: approved, lgtm, size/XL

#694 bump operator version to 1.7.0 for release 3.9.0
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#698 update kubeVersion to 1.19.0
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#700 add preserve-unknown-fields and correct WATCHNAMESPACE
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_operandconfigs.yaml
  config/crd/bases/operator.ibm.com_operandconfigs.yaml
Labels: approved, lgtm, size/XS

#703 revert master branch to 3.9.0 for cd release
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#704 fix: Remove service account from operator bundle manifest
  bundle.Dockerfile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  bundle/manifests/operand-deployment-lifecycle-manager_v1_serviceaccount.yaml
  bundle/metadata/annotations.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
Labels: approved, lgtm, size/S
