Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2021-04, with the labels that each got.

#646 update owners
  OWNERS
Labels: approved, lgtm, size/XS

#647 bump version to 1.4.3
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#648 updated ubi8 image to 8.3-298
  Dockerfile
Labels: approved, lgtm, size/XS

#645 feat: Apply the ALM example increment to existing CRs
  controllers/operandbindinfo/operandbindinfo_controller.go
  controllers/operandconfig/operandconfig_controller.go
  controllers/operandregistry/operandregistry_controller.go
  controllers/operandrequest/operandrequest_controller.go
  controllers/operandrequest/operandrequest_controller_test.go
  controllers/operandrequest/reconcile_operand.go
  controllers/operandrequest/reconcile_operator.go
Labels: approved, lgtm, size/L

#650 fix: Users can just create OperandRequest to install operator and CR …
  api/v1alpha1/operandrequest_types.go
  bundle.Dockerfile
  bundle/manifests/operator.ibm.com_operandrequests.yaml
  config/crd/bases/operator.ibm.com_operandrequests.yaml
  controllers/operandrequest/operandrequest_controller_test.go
  controllers/operandrequest/reconcile_operand.go
  controllers/operandrequest/reconcile_operator.go
  controllers/testutil/test_util.go
  docs/design/create-cr-by-operandrequest.md
  docs/design/operand-deployment-lifecycle-manager.md
  go.mod
Labels: approved, lgtm, size/L

#654 fetch ODLM_SCOPE and cache ODLM CRs
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/e2e/manager/manager.yaml
  config/manager/manager.yaml
  controllers/util/util.go
  main.go
Labels: approved, lgtm, size/S

#656 fix: make catalogsource information optional in the OperandRegistry. …
  api/v1alpha1/operandregistry_types.go
  bundle/manifests/operator.ibm.com_operandregistries.yaml
  config/crd/bases/operator.ibm.com_operandregistries.yaml
  controllers/operator/manager.go
  go.mod
  go.sum
  main.go
Labels: approved, lgtm, size/XL

#655 feat: ODLM can check the existing subscription by packagenames
  controllers/operator/manager.go
Labels: approved, lgtm, size/S

#657 fix: Add a timeout for deleting an operandrequest
  controllers/constant/constant.go
  controllers/operandrequest/operandrequest_controller_test.go
  controllers/operandrequest/reconcile_operand.go
  controllers/operandrequest/reconcile_operator.go
  controllers/testutil/test_util.go
  controllers/util/util.go
Labels: approved, lgtm, size/M

#658 fix: preserve unknown fields in OperandConfig
  api/v1alpha1/operandconfig_types.go
  bundle/manifests/operator.ibm.com_operandconfigs.yaml
  config/crd/bases/operator.ibm.com_operandconfigs.yaml
  controllers/operandrequest/operandrequest_controller_test.go
Labels: approved, lgtm, size/XS

#661 Reconcile two NSS CRs managedby ODLM
  controllers/constant/constant.go
  controllers/namespacescope/namespacescope_controler_test.go
  controllers/namespacescope/namespacescope_controller.go
  controllers/testutil/test_util.go
  go.mod
  main.go
Labels: approved, lgtm, size/L

#662 add imagepullpolicy
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: approved, lgtm, size/XS

#663 feat(Add warning message when can't find customresource in CSV):
  controllers/operandrequest/reconcile_operand.go
Labels: approved, lgtm, size/S

#664 fix codecov
  Makefile
Labels: approved, lgtm, size/XS

#665 fix: continue the loop when namespacescope cr is not found
  controllers/namespacescope/namespacescope_controller.go
Labels: approved, lgtm, size/XS

#666 bump version to 1.5.1
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#660 add complete err check
  controllers/operandrequest/reconcile_operand.go
Labels: approved, lgtm, size/S

#667 Add startingCSV into the OperandRegistry
  api/v1alpha1/operandconfig_types.go
  api/v1alpha1/operandregistry_types.go
  bundle/manifests/operator.ibm.com_operandregistries.yaml
  config/crd/bases/operator.ibm.com_operandregistries.yaml
  controllers/operandrequest/reconcile_operator.go
Labels: approved, lgtm, size/S

#668 change env var from ODLM_SCOPE to ISOLATED_MODE
  controllers/util/util.go
  main.go
Labels: approved, lgtm, size/S
