Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2021-07, with the labels that each got.

#705 Update readme in CSV
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  common/Makefile.common.mk
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  go.mod
  go.sum
Labels: approved, lgtm, size/XL

#706 Add health and ready probe
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  main.go
Labels: approved, lgtm, size/M

#708 chore: Add licenses used in the operator
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#716 bump version to 1.8.0
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#702 apply k8s PreserveUnknownFields into API
  api/v1alpha1/operandrequest_types.go
  bundle/manifests/operator.ibm.com_operandrequests.yaml
  config/crd/bases/operator.ibm.com_operandrequests.yaml
Labels: approved, lgtm, size/XS

#717 fix: Make probe more loose
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: approved, lgtm, size/S

#718 bump version to 1.7.1
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#685 change tag back to latest for base image
  Dockerfile
Labels: approved, lgtm, size/XS

#723 Get csv even the installPlan requires Approval
  controllers/operator/manager.go
Labels: approved, lgtm, size/XS

#724 Get csv even the installPlan requires Approval
  controllers/operator/manager.go
Labels: approved, lgtm, size/XS

#725 perf: shorten initial delay of readness probe
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: approved, lgtm, size/XS

#726 Get csv even the installPlan requires Approval (#723)
  controllers/operator/manager.go
Labels: approved, lgtm, size/XS
