Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2021-05, with the labels that each got.

#672 feat: list all the subscriptions in the namespace to find existing op…
  controllers/operator/manager.go
Labels: approved, lgtm, size/S

#671 feat: use patch command to manage resources finalizers
  Makefile
  controllers/operandbindinfo/operandbindinfo_controller.go
  controllers/operandrequest/operandrequest_controller.go
  controllers/operandrequest/operandrequest_controller_test.go
Labels: approved, lgtm, size/S

#674 feat: When OperandRegistry can't be found, adding a timestap into the…
  controllers/operandrequest/operandrequest_controller.go
  controllers/operandrequest/reconcile_operator.go
Labels: approved, lgtm, size/M

#676 Update OperandConfig Annotation
  controllers/operandrequest/reconcile_operator.go
Labels: approved, lgtm, size/XS

#678 fix: Make operandrequest can be removed together with the namespace d…
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/operandrequest/operandrequest_controller.go
Labels: approved, lgtm, size/M

#679 fix: When PackageManifest is not found, add the error message into co…
  api/v1alpha1/operandrequest_types.go
  controllers/operandrequest/reconcile_operator.go
  controllers/operator/manager.go
Labels: approved, lgtm, size/S

#669 feat: Install operators in batch.
  Makefile
  api/v1alpha1/operandrequest_types.go
  config/e2e/crd/bases/operator.ibm.com_namespacescopes.yaml
  config/e2e/crd/bases/operator.ibm.com_operandbindinfos.yaml
  config/e2e/crd/bases/operator.ibm.com_operandconfigs.yaml
  config/e2e/crd/bases/operator.ibm.com_operandregistries.yaml
  config/e2e/crd/bases/operator.ibm.com_operandrequests.yaml
  config/e2e/crd/kustomization.yaml
  config/e2e/kustomization.yaml
  controllers/namespacescope/namespacescope_controller.go
  controllers/operandrequest/operandrequest_controller.go
  controllers/operandrequest/operandrequest_controller_test.go
  controllers/operandrequest/operandrequest_suite_test.go
  controllers/operandrequest/reconcile_operand.go
  controllers/operandrequest/reconcile_operator.go
  controllers/operator/manager.go
  main.go
Labels: approved, lgtm, size/XXL
