Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2021-11, with the labels that each got.

#762 bump version to 1.12.0
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#764 update golang to version 1.17.3 for EUS
  Dockerfile
  go.mod
Labels: approved, lgtm, size/M

#763 go mod tidy for golang 1.17
  go.mod
Labels: approved, lgtm, size/M

#765 compare the hash of data section for Job resource to determine whether to update the Job template
  controllers/constant/constant.go
  controllers/operandrequest/reconcile_operand.go
Labels: approved, lgtm, size/M

#766 Update the string splitter in OperandConfig status
  controllers/operandconfig/operandconfig_controller.go
Labels: size/XS, approved, lgtm
