Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2021-08, with the labels that each got.

#727 opt-in of ubi base image automated builds
  Dockerfile
  Makefile
  base-images.json
  common/scripts/artifactory_config_docker.sh
Labels: size/XS, approved, lgtm

#729 add relatedImages to operator CSV
  bundle.Dockerfile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#734 bump version to 1.9.0
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#733 make operatorconfig optional
  controllers/operandrequest/reconcile_operand.go
  controllers/operandrequest/reconcile_operator.go
Labels: approved, lgtm, size/M

#736 build: bump k8s dependencies to 1.21
  .gitignore
  Makefile
  common/Makefile.common.mk
  controllers/namespacescope/namespacescope_suite_test.go
  controllers/operandbindinfo/operandbindinfo_suite_test.go
  controllers/operandconfig/operandconfig_suite_test.go
  controllers/operandregistry/operandregistry_suite_test.go
  controllers/operandrequest/operandrequest_suite_test.go
  controllers/operandrequest/reconcile_operand.go
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#737 fix: Operator only reconciles when watched subscriptions are updated.
  controllers/operandrequest/operandrequest_controller.go
Labels: size/XS, approved, lgtm

#740 using v0.6.2 version envtest
  Makefile
Labels: size/XS, approved, lgtm

#739 opt-in of ubi base image automated builds (#727)
  Dockerfile
  Makefile
  base_images.json
  common/scripts/artifactory_config_docker.sh
Labels: size/XS, approved, lgtm
