Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2022-09, with the labels that each got.

#833 odlm version bump to 3.19.5
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#836 update version bump script by using "sed"
  common/scripts/next-csv.sh
Labels: approved, lgtm, size/M

#834 [release-ltsr] add excluded CatalogSource annotation for Registry
  controllers/operator/manager.go
  controllers/util/util.go
Labels: approved, lgtm, size/S

#840 [LTSR] Update version bump script
  common/scripts/next-csv.sh
Labels: approved, lgtm, size/M

#841 Removed partial installplan condition checks and added csv check in operand reconciliation
  controllers/operandrequest/reconcile_operand.go
Labels: approved, lgtm, size/M

#842 odlm version bump to 1.20.0
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#843 [ODLM] cherry-pick installplan check
  controllers/operandrequest/reconcile_operand.go
Labels: approved, lgtm, size/M

#844 keep minkube version unchanged in version bump script
  common/scripts/next-csv.sh
Labels: size/XS, approved, lgtm

#847 downgrade log level
  controllers/operator/manager.go
Labels: size/XS, approved, lgtm

#846 upgrade log level
  controllers/operator/manager.go
Labels: size/XS, approved, lgtm
