Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2022-03, with the labels that each got.

#797 chore: Update operator version to 1.15.0
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#798 bump ODLM efix versions for cs v3.16.2 fix
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#799 fix: remove the operator checker for the operator upgrade
  controllers/operatorchecker/operatorchecker_controller.go
Labels: approved, lgtm, size/S

#800 fix: remove the operator checker for the operator upgrade
  controllers/operatorchecker/operatorchecker_controller.go
  controllers/util/util.go
Labels: approved, lgtm, size/M

#796 fix: When operandrequest is empty then set OperandRequest to running …
  api/v1alpha1/operandrequest_types.go
Labels: size/XS, approved, lgtm

#807 Revert "fix: When operandrequest is empty then set OperandRequest to running …"
  api/v1alpha1/operandrequest_types.go
Labels: size/XS, approved, lgtm
