Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2022-11, with the labels that each got.

#861 New prow cluster name
  common/Makefile.common.mk
Labels: size/XS, approved, lgtm

#862 New prow cluster name
  common/Makefile.common.mk
Labels: size/XS

#863 New prow cluster name
  common/Makefile.common.mk
Labels: size/XS, approved

#864 remove csv phase check (IBM#853)
  base_images.json
  controllers/operandrequest/reconcile_operand.go
Labels: approved, lgtm, size/S

#866 remove quay image build support
  Makefile
Labels: approved, lgtm

#865 remove quay image build support
  Makefile
Labels: approved, lgtm
