Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2022-01, with the labels that each got.

#772 update status of deprecated service to not found
  api/v1alpha1/operandconfig_types.go
  api/v1alpha1/operandrequest_types.go
  controllers/operandrequest/reconcile_operand.go
Labels: size/XS, approved, lgtm

#775 refactor: refactor CSV fetcher and operator status checker
  controllers/operandrequest/reconcile_operand.go
  controllers/operator/manager.go
Labels: approved, lgtm, size/M

#777 fix: Set creating status if the target CR is not found
  controllers/operandconfig/operandconfig_controller.go
Labels: size/XS, approved, lgtm

#776 add operator recover logic with OperatorChecker
  api/v1alpha1/zz_generated.deepcopy.go
  controllers/operatorchecker/operatorchecker_controller.go
  main.go
Labels: approved, lgtm, size/L

#779 Get new instance to check latest status
  controllers/operandrequest_controller.go
Labels: size/XS, approved, lgtm

#778 update status check for deprecated services
  controllers/operandrequest/reconcile_operator.go
Labels: size/XS, approved, lgtm

#781 update the copyrights for 2022 in EUS
  Makefile
  api/v1alpha1/finalizer.go
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/operandbindinfo_types.go
  api/v1alpha1/operandconfig_types.go
  api/v1alpha1/operandregistry_types.go
  api/v1alpha1/operandrequest_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  common/Makefile.common.mk
  common/scripts/.githooks/make_lint-all.sh
  common/scripts/artifactory_config_docker.sh
  common/scripts/codecov.sh
  common/scripts/create_bundle.sh
  common/scripts/gobuild.sh
  common/scripts/install-kubebuilder.sh
  common/scripts/install-operator-sdk.sh
  common/scripts/install-opm.sh
  common/scripts/lint_copyright_banner.sh
  common/scripts/lint_go.sh
  common/scripts/multiarch_image.sh
  common/scripts/next-csv.sh
  common/scripts/push-csv.sh
  common/scripts/quay_config_docker.sh
  controllers/common/fetch.go
  controllers/constant/constant.go
  controllers/k8sutil/cache.go
  controllers/namespacescope_controller.go
  controllers/namespacescope_controller_test.go
  controllers/operandbindinfo_controller.go
  controllers/operandbindinfo_controller_test.go
  controllers/operandconfig_controller.go
  controllers/operandconfig_controller_test.go
  controllers/operandregistry_controller.go
  controllers/operandregistry_controller_test.go
  controllers/operandrequest_controller.go
  controllers/operandrequest_controller_test.go
  controllers/reconcile_operand.go
  controllers/reconcile_operator.go
  controllers/suite_test.go
  controllers/testutil/test_data.go
  controllers/util/merge.go
  controllers/util/merge_test.go
  controllers/util/multi_errors.go
  controllers/util/multi_errors_test.go
  controllers/util/util.go
  controllers/util/util_suite_test.go
  controllers/util/util_test.go
  hack/boilerplate.go.txt
  main.go
  version/version.go
Labels: approved, lgtm, size/L

#782 operator recovery logic
  controllers/constant/constant.go
  controllers/operatorchecker/operatorchecker_controller.go
Labels: approved, lgtm, size/L
