Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2023-05, with the labels that each got.

#926 bump ODLM version to 1.21.4 for 3.23.4
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, size/S

#927 Update test case
  Makefile
  api/v1alpha1/operandrequest_types.go
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_operandregistries.yaml
  bundle/manifests/operator.ibm.com_operandrequests.yaml
  common/Makefile.common.mk
  common/scripts/install-olm.sh
  config/crd/bases/operator.ibm.com_operandregistries.yaml
  config/crd/bases/operator.ibm.com_operandrequests.yaml
  config/samples/operator_v1alpha1_operandconfig.yaml
  config/samples/operator_v1alpha1_operandregistry.yaml
  config/samples/operator_v1alpha1_operandrequest.yaml
  controllers/namespacescope/namespacescope_suite_test.go
  controllers/operandbindinfo/operandbindinfo_suite_test.go
  controllers/operandconfig/operandconfig_controller_test.go
  controllers/operandconfig/operandconfig_suite_test.go
  controllers/operandregistry/operandregistry_controller_test.go
  controllers/operandregistry/operandregistry_suite_test.go
  controllers/operandrequest/operandrequest_controller.go
  controllers/operandrequest/operandrequest_controller_test.go
  controllers/operandrequest/operandrequest_suite_test.go
  controllers/operandrequest/reconcile_operand.go
  controllers/testutil/test_data.go
  controllers/testutil/test_util.go
  go.mod
  go.sum
  test/e2e/constants.go
  test/e2e/e2e_suite_test.go
  test/e2e/helpers_test.go
  test/e2e/odlm_test.go
  test/e2e/utils_test.go
Labels: approved, lgtm, size/XXL

#925 odlm annotation updated for nss operator
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
Labels: size/XS, approved, lgtm

#928 update go to latest
  Dockerfile
Labels: size/XS, approved, lgtm

#929 Update go to 1.20.4
  Dockerfile
Labels: size/XS, approved, lgtm

#930 manage complete tenant scope for subscriptions
  controllers/operandconfig/operandconfig_controller.go
  controllers/operandrequest/reconcile_operand.go
  controllers/operandrequest/reconcile_operator.go
  controllers/operator/manager.go
Labels: approved, lgtm, size/L

#931 update packages for twistlock
  go.mod
  go.sum
Labels: size/XS, approved, lgtm
