Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2023-09, with the labels that each got.

#968 Add OperandBindinfo example into alm-example
  api/v1alpha1/operandbindinfo_types.go
  api/v1alpha1/operandconfig_types.go
  api/v1alpha1/operandregistry_types.go
  api/v1alpha1/operandrequest_types.go
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_operandbindinfos.yaml
  bundle/manifests/operator.ibm.com_operandconfigs.yaml
  bundle/manifests/operator.ibm.com_operandregistries.yaml
  config/crd/bases/operator.ibm.com_operandbindinfos.yaml
  config/crd/bases/operator.ibm.com_operandconfigs.yaml
  config/crd/bases/operator.ibm.com_operandregistries.yaml
  config/samples/kustomization.yaml
  config/samples/operator_v1alpha1_operandbindinfo.yaml
  controllers/operandrequest/operandrequest_controller.go
Labels: approved, lgtm, size/M

#961 add ephemeral-storage request to container
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: size/XS, approved, lgtm

#971 Bump ODLM to v4.3 version
  Makefile
  bundle.Dockerfile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#970 Add the common label to operand Pod
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
Labels: size/XS, approved, lgtm
