Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2023-10, with the labels that each got.

#973 Add OperandBindinfo example into alm-example
  api/v1alpha1/operandbindinfo_types.go
  api/v1alpha1/operandconfig_types.go
  api/v1alpha1/operandregistry_types.go
  api/v1alpha1/operandrequest_types.go
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_operandbindinfos.yaml
  bundle/manifests/operator.ibm.com_operandconfigs.yaml
  bundle/manifests/operator.ibm.com_operandregistries.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/operator.ibm.com_operandbindinfos.yaml
  config/crd/bases/operator.ibm.com_operandconfigs.yaml
  config/crd/bases/operator.ibm.com_operandregistries.yaml
  config/crd/bases/operator.ibm.com_operandrequests.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/samples/kustomization.yaml
  config/samples/operator_v1alpha1_operandbindinfo.yaml
Labels: approved, lgtm, size/M

#976 bump ODLM to 1.21.9 for LTSR 3.23.9
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#980 list out basic permission needed by ODLM
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/rbac/role.yaml
Labels: approved, lgtm, size/M

#981 Add additional explicitly listed permission
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
Labels: approved, lgtm, size/M

#982 update go, net pkg
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#985 add finalizers permission
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/rbac/role.yaml
Labels: size/XS, approved, lgtm

#984 [LTSR] set OwnerReference for resources created by OperandRequest
  controllers/operandrequest/reconcile_operand.go
Labels: approved, lgtm, size/S

#983 set OwnerReference for resources created by OperandRequest
  controllers/operandrequest/reconcile_operand.go
Labels: approved, lgtm, size/S

#986 update grpc to 1.59.0
  go.mod
  go.sum
Labels: approved, lgtm, size/M
