Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2023-01, with the labels that each got.

#875 avoid marking running status when it hits error
  controllers/operandrequest/reconcile_operand.go
Labels: size/XS, approved, lgtm

#873 avoid marking running status when it hits error
  controllers/operandrequest/reconcile_operand.go
Labels: size/XS, approved, lgtm

#876 bump version for 3.19.8
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#877 Resolve version conflict in OperandRequest - Basic iteration
  controllers/operandrequest/reconcile_operand.go
  controllers/operandrequest/reconcile_operator.go
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#879 refresh pod only when secret and configmap updated
  controllers/operandbindinfo/operandbindinfo_controller.go
Labels: approved, lgtm, size/M

#880 refresh pod only when secret and configmap updated
  controllers/operandbindinfo/operandbindinfo_controller.go
Labels: approved, lgtm, size/M

#882 remove serviceNamespace
  api/v1alpha1/operandregistry_types.go
  bundle/manifests/operator.ibm.com_operandregistries.yaml
  config/crd/bases/operator.ibm.com_operandregistries.yaml
  controllers/operandbindinfo/operandbindinfo_controller.go
  controllers/operandconfig/operandconfig_controller.go
  controllers/operandrequest/operandrequest_controller_test.go
  controllers/operandrequest/reconcile_operand.go
  controllers/operandrequest/reconcile_operator.go
  controllers/operator/manager.go
  controllers/testutil/test_util.go
  docs/design/operand-deployment-lifecycle-manager.md
  test/e2e/helpers_test.go
  test/e2e/odlm_test.go
Labels: approved, lgtm, size/L

#883 update go to 1.19.4
  Dockerfile
Labels: size/XS, approved, lgtm

#884 new artifactory image endpoint (odlm)
  Dockerfile
  Makefile
  common/scripts/artifactory_config_docker.sh
Labels: approved, lgtm, size/S

#885 [ltsr] new artifactory image endpoint (odlm)
  Dockerfile
  Makefile
  common/scripts/artifactory_config_docker.sh
Labels: approved, lgtm, size/S

#886 [future] new artifactory image endpoint (odlm)
  Dockerfile
  Makefile
  common/scripts/artifactory_config_docker.sh
Labels: approved, lgtm, size/S

#887 Enhance uninstalltion for multiVersion resolution
  controllers/operandrequest/reconcile_operator.go
Labels: approved, lgtm, size/S

#889 bump version to 1.21.1 for 3.23.1
  Makefile
  bundle.Dockerfile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#888 add tombstone parameter in OperandRegistry
  Makefile
  api/v1alpha1/operandregistry_types.go
  api/v1alpha1/operandrequest_types.go
  bundle/manifests/operator.ibm.com_operandregistries.yaml
  config/crd/bases/operator.ibm.com_operandregistries.yaml
  controllers/operandrequest/reconcile_operator.go
  controllers/operator/manager.go
  docs/design/operand-deployment-lifecycle-manager.md
Labels: approved, lgtm, size/M
