Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2023-11, with the labels that each got.

#989 fix for failing to list packagemanifests resource
  Makefile
  bundle.Dockerfile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/rbac/role.yaml
Labels: approved, lgtm, size/XL

#990 Add value reference in OperandConfig
  controllers/constant/constant.go
  controllers/operandbindinfo/operandbindinfo_controller.go
  controllers/operandrequest/operandrequest_controller.go
  controllers/operandrequest/operandrequest_controller_test.go
  controllers/operandrequest/reconcile_operand.go
  controllers/operator/manager.go
  controllers/testutil/test_util.go
  controllers/util/util.go
  go.mod
  main.go
Labels: approved, lgtm, size/XL

#991 update grpc pkg
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#992 Add support for sharing Route data via ConfigMap with OperandBindInfo
  Makefile
  api/v1alpha1/operandbindinfo_types.go
  api/v1alpha1/operandrequest_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle.Dockerfile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_operandbindinfos.yaml
  bundle/manifests/operator.ibm.com_operandrequests.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/operator.ibm.com_operandbindinfos.yaml
  config/crd/bases/operator.ibm.com_operandrequests.yaml
  config/e2e/crd/bases/operator.ibm.com_operandbindinfos.yaml
  config/e2e/crd/bases/operator.ibm.com_operandrequests.yaml
  controllers/operandbindinfo/operandbindinfo_controller.go
  controllers/operandbindinfo/operandbindinfo_suite_test.go
  controllers/testutil/test_util.go
  controllers/util/util.go
  go.mod
  go.sum
  main.go
  test/e2e/helpers_test.go
Labels: approved, lgtm, size/XXL

#993 Add support for sharing Service data via ConfigMap with OperandBindInfo
  api/v1alpha1/operandbindinfo_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_operandbindinfos.yaml
  bundle/manifests/operator.ibm.com_operandrequests.yaml
  config/crd/bases/operator.ibm.com_operandbindinfos.yaml
  config/crd/bases/operator.ibm.com_operandrequests.yaml
  config/e2e/crd/bases/operator.ibm.com_operandbindinfos.yaml
  config/e2e/crd/bases/operator.ibm.com_operandrequests.yaml
  controllers/operandbindinfo/operandbindinfo_controller.go
  controllers/util/util.go
Labels: approved, lgtm, size/L

#994 Support jsonpath in OperandConfig value reference
  controllers/operandbindinfo/operandbindinfo_controller.go
  controllers/operator/manager.go
  controllers/util/util.go
Labels: approved, lgtm, size/M

#997 bump version for LTSR 3.19.18
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#998 Bump ODLM to 4.2.2
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  common/scripts/next-csv.sh
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#999 allow to add multiple owners to cm/secret
  controllers/operandbindinfo/operandbindinfo_controller.go
  controllers/operandrequest/reconcile_operand.go
  controllers/util/util.go
Labels: approved, lgtm, size/M

#1000 [LTSR] allow to add multiple owner references to cm/secret
  controllers/operandbindinfo/operandbindinfo_controller.go
  controllers/operandrequest/reconcile_operand.go
Labels: approved, lgtm, size/M
