Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2023-04, with the labels that each got.

#917 bump ODLM version to 1.21.3 for 3.23.3
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#918 bump go for 3.23.3
  Dockerfile
Labels: size/XS, approved, lgtm

#916 check for status.services, im service status
  api/v1alpha1/operandrequest_types.go
  controllers/operandrequest/operandrequest_controller.go
  controllers/operandrequest/reconcile_operand.go
Labels: approved, lgtm, size/L

#920 cp3 migrate to aws
  common/Makefile.common.mk
Labels: size/XS, approved, lgtm

#919 LTSR migrate to aws
  common/Makefile.common.mk
Labels: size/XS, approved, lgtm

#922 Remove the status.services entry for an operator if it is removed from an operandrequest
  api/v1alpha1/operandrequest_types.go
  controllers/operandrequest/reconcile_operator.go
Labels: approved, lgtm, size/S

#921 Indicate multi requested service version conflict
  api/v1alpha1/operandrequest_types.go
  controllers/operandrequest/reconcile_operand.go
  controllers/operandrequest/reconcile_operator.go
  controllers/operator/manager.go
Labels: approved, lgtm, size/M
