Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2023-02, with the labels that each got.

#891 skip reconcile CR when it only exists in alm-example, not OperandConfig
  controllers/operandrequest/reconcile_operand.go
Labels: size/XS, approved, lgtm

#892 [future] skip reconcile CR when it only exists in alm-example, not OperandConfig
  controllers/operandrequest/reconcile_operand.go
Labels: size/XS, approved, lgtm

#896 update status for services marked as tombstone
  controllers/operandrequest/reconcile_operator.go
Labels: size/XS, approved, lgtm

#897 update pkg for twistlock
  go.mod
  go.sum
Labels: size/XS, approved, lgtm

#901 bump version to 4.0.0
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#894 ODLM updated status projection
  api/v1alpha1/operandconfig_types.go
  api/v1alpha1/operandrequest_types.go
  bundle/manifests/operator.ibm.com_operandrequests.yaml
  controllers/k8sutil/cache.go
  controllers/operandrequest/reconcile_operand.go
  controllers/util/util.go
  go.mod
  go.sum
  test/e2e/helpers_test.go
Labels: approved, lgtm, size/L
