Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2023-03, with the labels that each got.

#904 bump odlm to 3.23.2
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#907 tolerate multi entries for same subscription
  common/config/.golangci.yml
  controllers/operandrequest/operandrequest_controller.go
  controllers/operandrequest/reconcile_operand.go
  controllers/operandrequest/reconcile_operator.go
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#910 skip sub updating for discontinued services
  controllers/operandrequest/reconcile_operator.go
Labels: approved, lgtm, size/M

#911 update go mod to 1.20
  Dockerfile
  api/v1alpha1/operandconfig_types.go
  api/v1alpha1/operandrequest_types.go
  controllers/k8sutil/cache.go
  controllers/util/util.go
  go.mod
  go.sum
  test/e2e/helpers_test.go
Labels: approved, lgtm, size/S

#912 update pkgs for twistlock
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#913 add preserve unknown fields to operandrequest status
  bundle/manifests/operator.ibm.com_operandrequests.yaml
Labels: size/XS, approved, lgtm

#914 tolerate multi catalogsource for same service
  controllers/operandrequest/reconcile_operator.go
Labels: approved, lgtm, size/S
