Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2023-07, with the labels that each got.

#943 update go for 4.1
  Dockerfile
Labels: size/XS, approved, lgtm

#944 multiple opbi
  controllers/operandbindinfo/operandbindinfo_controller.go
Labels: approved, lgtm, size/S

#945 bump version for 3.19.14
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#946 updated dependapot to cover release-ltsr branch
  .github/dependabot.yml
Labels: size/XS, approved, lgtm

#950 Compare updated opreq status with latest opreq
  controllers/operandrequest/operandrequest_controller.go
Labels: approved, lgtm, size/S

#949 [LTSR] update e2e testcases
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_operandregistries.yaml
  bundle/manifests/operator.ibm.com_operandrequests.yaml
  common/Makefile.common.mk
  common/scripts/install-olm.sh
  config/crd/bases/operator.ibm.com_operandregistries.yaml
  config/crd/bases/operator.ibm.com_operandrequests.yaml
  config/samples/operator_v1alpha1_operandconfig.yaml
  config/samples/operator_v1alpha1_operandregistry.yaml
  config/samples/operator_v1alpha1_operandrequest.yaml
  controllers/namespacescope/namespacescope_suite_test.go
  controllers/operandbindinfo/operandbindinfo_suite_test.go
  controllers/operandconfig/operandconfig_controller_test.go
  controllers/operandconfig/operandconfig_suite_test.go
  controllers/operandregistry/operandregistry_controller_test.go
  controllers/operandregistry/operandregistry_suite_test.go
  controllers/operandrequest/operandrequest_controller.go
  controllers/operandrequest/operandrequest_controller_test.go
  controllers/operandrequest/operandrequest_suite_test.go
  controllers/operandrequest/reconcile_operand.go
  controllers/testutil/test_data.go
  controllers/testutil/test_util.go
  go.mod
  go.sum
  test/e2e/constants.go
  test/e2e/e2e_suite_test.go
  test/e2e/helpers_test.go
  test/e2e/odlm_test.go
  test/e2e/utils_test.go
Labels: approved, lgtm, size/XXL

#951 update go, logrus for 3.19.14
  Dockerfile
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#952 update go-restful pkg for 3.19.14
  go.mod
  go.sum
Labels: size/XS, approved, lgtm
