Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2024-08, with the labels that each got.

#1065 Clean redundant CSV in service ns during the migration
  controllers/operandrequest/reconcile_operand.go
  controllers/operator/manager.go
Labels: approved, lgtm, size/M

#1066 Find semantic versioning from channel
  controllers/operandrequest/reconcile_operator.go
  controllers/util/util.go
  controllers/util/util_test.go
Labels: approved, lgtm, size/L

#1071 add securityContext .seccompProfile field
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/e2e/manager/manager.yaml
  config/manager/manager.yaml
Labels: size/XS, approved, lgtm

#1074 Bump version to 4.3.5 for SC2 4.6.6
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#1076 update golangci version to 1.60.x
  Dockerfile
  common/config/.golangci.yml
  common/scripts/lint_go.sh
  controllers/operandregistry/operandregistry_controller.go
  controllers/operandrequest/reconcile_operand.go
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#1075 remove ltsr branch from dependabot.yml
  .github/dependabot.yml
Labels: size/XS, approved, lgtm

#1077 updated base image to ubi9
  Dockerfile
Labels: size/XS, approved, lgtm

#1078 added feature to handle user managed operators (BYO)
  Makefile
  api/v1alpha1/operandregistry_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_operandregistries.yaml
  common/Makefile.common.mk
  common/scripts/lint_go.sh
  config/crd/bases/operator.ibm.com_operandregistries.yaml
  controllers/operandrequest/operandrequest_controller.go
  controllers/operandrequest/reconcile_operand.go
  controllers/operandrequest/reconcile_operator.go
  controllers/operandrequest/reconcile_operator_test.go
  controllers/operator/manager.go
Labels: approved, lgtm, size/L

#1079 implement channel fallback in catalog discovery
  api/v1alpha1/operandregistry_types.go
  bundle/manifests/operator.ibm.com_operandregistries.yaml
  config/crd/bases/operator.ibm.com_operandregistries.yaml
  controllers/operandbindinfo/operandbindinfo_suite_test.go
  controllers/operandconfig/operandconfig_suite_test.go
  controllers/operandregistry/operandregistry_suite_test.go
  controllers/operandrequest/operandrequest_suite_test.go
  controllers/operandrequest/reconcile_operand.go
  controllers/operandrequest/reconcile_operator.go
  controllers/operandrequest/reconcile_operator_test.go
  controllers/operator/manager.go
  controllers/operator/manager_test.go
  controllers/operatorconfig/operatorconfig_suite_test.go
  controllers/util/util.go
  controllers/util/util_test.go
Labels: approved, lgtm, size/XL
