Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2024-10, with the labels that each got.

#1089 Bump version to 4.3.7 fo SC2 4.6.8
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#1090 Revert "build(deps): bump golang from 1.23.0-bullseye to 1.23.1-bullseye"
  Dockerfile
Labels: size/XS

#1091 Move to bookworm golang image
  Dockerfile
Labels: size/XS, approved, lgtm

#1092 label length limitation
  controllers/constant/constant.go
  controllers/operandrequest/operandrequest_controller.go
  controllers/operator/manager.go
  controllers/util/util.go
Labels: approved, lgtm, size/M

#1093 fix typo in utils function
  controllers/util/util.go
Labels: size/XS, approved, lgtm

#1094 ensure label within length limitation
  controllers/operator/manager.go
Labels: size/XS, approved, lgtm

#1095 Delete k8s resources by checking the label from OperandConfig
  controllers/operandrequest/reconcile_operand.go
Labels: approved, lgtm, size/L
