Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2024-03, with the labels that each got.

#1022 Update CRD to add preserve unknown fields
  Makefile
  api/v1alpha1/operandconfig_types.go
  api/v1alpha1/operandregistry_types.go
  bundle.Dockerfile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_operandbindinfos.yaml
  bundle/manifests/operator.ibm.com_operandconfigs.yaml
  bundle/manifests/operator.ibm.com_operandregistries.yaml
  bundle/manifests/operator.ibm.com_operandrequests.yaml
  bundle/metadata/annotations.yaml
  bundle/tests/scorecard/config.yaml
  config/crd/bases/operator.ibm.com_operandbindinfos.yaml
  config/crd/bases/operator.ibm.com_operandconfigs.yaml
  config/crd/bases/operator.ibm.com_operandregistries.yaml
  config/crd/bases/operator.ibm.com_operandrequests.yaml
Labels: approved, lgtm, size/XXL

#1023 add CertManager and AuditLogging CR cluster permission to ODLM
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/rbac/role.yaml
Labels: approved, lgtm, size/M

#1025 Introduce OwnReference API
  Makefile
  api/v1alpha1/operandconfig_types.go
  bundle.Dockerfile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_operandconfigs.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/operator.ibm.com_operandconfigs.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  controllers/operandrequest/reconcile_operand.go
  controllers/operandrequest/reconcile_operand_test.go
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#1019 Enable deep JSON merging for Kubernetes resources when updating them
  controllers/operandrequest/reconcile_operand.go
  controllers/util/merge.go
Labels: approved, lgtm, size/L

#1029 Update deepcopy library for any type deep copying
  controllers/operandrequest/reconcile_operand.go
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#1027 scaffolded OperatorConfig API
  PROJECT
  api/v1alpha1/operatorconfig_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle.Dockerfile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_operatorconfigs.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/operator.ibm.com_operatorconfigs.yaml
  config/crd/kustomization.yaml
  config/crd/patches/label_in_operatorconfigs.yaml
  config/rbac/operatorconfig_editor_role.yaml
  config/rbac/operatorconfig_viewer_role.yaml
  config/samples/operator_v1alpha1_operatorconfig.yaml
  controllers/operatorconfig/operatorconfig_controller.go
  controllers/operatorconfig/operatorconfig_suite_test.go
  go.mod
  go.sum
  main.go
Labels: approved, lgtm, size/XL
