Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2024-06, with the labels that each got.

#1049 Fix operand phase error for Elasticsearch in OperandRequest
  api/v1alpha1/operandrequest_types.go
  controllers/operandrequest/operandrequest_controller.go
  controllers/operandrequest/reconcile_operand.go
Labels: approved, lgtm, size/S

#1050 Skip catalog discover when operator is not found in OperandRegistry
  controllers/operator/manager.go
Labels: size/XS, approved, lgtm

#1053 reconcile k8s resource in parallel and with retry logic
  controllers/constant/constant.go
  controllers/operandrequest/reconcile_operand.go
  controllers/operator/manager.go
  controllers/operatorconfig/operatorconfig_controller.go
  main.go
Labels: approved, lgtm, size/L

#1055 Find CSVs by label for an operator, to ensure deleting all the CSVs for a specific subscription
  controllers/operandconfig/operandconfig_controller_test.go
  controllers/operandregistry/operandregistry_controller_test.go
  controllers/operandrequest/operandrequest_controller_test.go
  controllers/operandrequest/reconcile_operator.go
  controllers/operator/manager.go
  controllers/testutil/test_util.go
Labels: approved, lgtm, size/L

#1056 Refactor members and services status update
  api/v1alpha1/operandrequest_types.go
  controllers/constant/constant.go
  controllers/operandrequest/operandrequest_controller.go
  controllers/operandrequest/reconcile_operand.go
Labels: approved, lgtm, size/L

#1058 Bump version to 4.3.3 for SC2 4.6.4
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#1057 Security update for June '24 LTSR release
  common/Makefile.common.mk
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#1059 Add webhook to replicate operandrequest in partial watched namespace
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  controllers/constant/constant.go
  controllers/util/util.go
  controllers/webhooks/operandrequestreplication/operandrequest_mutating_webhook.go
  controllers/webhooks/operandrequestreplication/operandrequest_mutating_webhook_test.go
  controllers/webhooks/operator_webhook.go
  controllers/webhooks/rules.go
  controllers/webhooks/webhook_register.go
  controllers/webhooks/webhookreconciler.go
  go.mod
  go.sum
  main.go
Labels: approved, lgtm, size/XXL
