Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2024-11, with the labels that each got.

#1096 Bump version to 4.3.8 for CS 4.6.9
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#1098 Tolerate both opt.channel and opt.FallbackChannels for one operator
  controllers/operandrequest/operandrequest_controller.go
  controllers/operandrequest/reconcile_operator.go
Labels: size/XS, approved, lgtm

#1099 Discover private CatalogSource only if no catalog cluster permission exists
  controllers/operator/manager.go
  controllers/operator/manager_test.go
Labels: approved, lgtm, size/M

#1100 Use SelfSubjectAccessReview to check ODLM's permission on getting catalog
  controllers/operator/manager.go
  controllers/operator/manager_test.go
Labels: approved, lgtm, size/S
