Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2024-02, with the labels that each got.

#1014 bump version for LTSR 3.19.21
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#1015 Improve logs on Catalog discovery
  controllers/operator/manager.go
Labels: size/XS, approved, lgtm

#1009 Reduce CPU and Memory usage
  controllers/operator/manager.go
Labels: size/XS, approved, lgtm

#1016 Prioritize the Catalog which ODLM is deployed from
  controllers/operator/manager.go
Labels: approved, lgtm, size/M

#1017 Read Object from k8s API directly instead of cache to avoid getting outdated object
  controllers/operator/manager.go
Labels: size/XS, approved, lgtm

#1018 Skip OperandRequest for OperandBindinfo if the OperandRequest is in the deletion status
  controllers/operandbindinfo/operandbindinfo_controller.go
Labels: size/XS, approved, lgtm
