Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2024-05, with the labels that each got.

#1043 Update pkgs for security vulnerabilities for 4.6.2
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#1039 Update ODLM module to match major version v4
  PROJECT
  controllers/namespacescope/namespacescope_controler_test.go
  controllers/namespacescope/namespacescope_controller.go
  controllers/namespacescope/namespacescope_suite_test.go
  controllers/operandbindinfo/operandbindinfo_controller.go
  controllers/operandbindinfo/operandbindinfo_controller_test.go
  controllers/operandbindinfo/operandbindinfo_suite_test.go
  controllers/operandconfig/operandconfig_controller.go
  controllers/operandconfig/operandconfig_controller_test.go
  controllers/operandconfig/operandconfig_suite_test.go
  controllers/operandregistry/operandregistry_controller.go
  controllers/operandregistry/operandregistry_controller_test.go
  controllers/operandregistry/operandregistry_suite_test.go
  controllers/operandrequest/operandrequest_controller.go
  controllers/operandrequest/operandrequest_controller_test.go
  controllers/operandrequest/operandrequest_suite_test.go
  controllers/operandrequest/reconcile_operand.go
  controllers/operandrequest/reconcile_operand_test.go
  controllers/operandrequest/reconcile_operator.go
  controllers/operandrequest/reconcile_operator_test.go
  controllers/operator/manager.go
  controllers/operatorchecker/operatorchecker_controller.go
  controllers/operatorconfig/operatorconfig_controller.go
  controllers/operatorconfig/operatorconfig_suite_test.go
  controllers/testutil/test_util.go
  go.mod
  main.go
  test/e2e/helpers_test.go
  test/e2e/odlm_test.go
  test/e2e/utils_test.go
Labels: approved, lgtm, size/L

#1046 Bump version to 1.21.13 for LTSR 3.19.22
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#1047 Bump ODLM to 4.3.2 for 4.6.3
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  common/Makefile.common.mk
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#1048 Only discover catalog for an operator when it has been requested in OperandRequest
  controllers/operandbindinfo/operandbindinfo_controller.go
  controllers/operandrequest/operandrequest_controller.go
  controllers/operandrequest/reconcile_operand.go
  controllers/operandrequest/reconcile_operator.go
  controllers/operator/manager.go
  controllers/operatorconfig/operatorconfig_controller.go
  controllers/util/merge.go
Labels: approved, lgtm, size/L
