Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2024-04, with the labels that each got.

#1030 Operatorconfig controller
  api/v1alpha1/operandregistry_types.go
  api/v1alpha1/operatorconfig_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_operandregistries.yaml
  bundle/manifests/operator.ibm.com_operatorconfigs.yaml
  config/crd/bases/operator.ibm.com_operandregistries.yaml
  config/crd/bases/operator.ibm.com_operatorconfigs.yaml
  config/rbac/role.yaml
  controllers/operatorconfig/operatorconfig_controller.go
  go.mod
Labels: approved, lgtm, size/XXL

#1028 Support uninstallation on intra-dependency
  Makefile
  api/v1alpha1/operandbindinfo_types.go
  api/v1alpha1/operandconfig_types.go
  api/v1alpha1/operandregistry_types.go
  api/v1alpha1/operandrequest_types.go
  api/v1alpha1/operatorconfig_types.go
  bundle.Dockerfile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_operandbindinfos.yaml
  bundle/manifests/operator.ibm.com_operandconfigs.yaml
  bundle/manifests/operator.ibm.com_operandregistries.yaml
  bundle/manifests/operator.ibm.com_operandrequests.yaml
  bundle/manifests/operator.ibm.com_operatorconfigs.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/operator.ibm.com_operandbindinfos.yaml
  config/crd/bases/operator.ibm.com_operandconfigs.yaml
  config/crd/bases/operator.ibm.com_operandregistries.yaml
  config/crd/bases/operator.ibm.com_operandrequests.yaml
  config/crd/bases/operator.ibm.com_operatorconfigs.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/constant/constant.go
  controllers/operandbindinfo/operandbindinfo_controller.go
  controllers/operandconfig/operandconfig_controller.go
  controllers/operandregistry/operandregistry_controller.go
  controllers/operandrequest/operandrequest_controller.go
  controllers/operandrequest/reconcile_operand.go
  controllers/operandrequest/reconcile_operator.go
  controllers/operandrequest/reconcile_operator_test.go
  controllers/operatorconfig/operatorconfig_controller.go
  controllers/util/util.go
  controllers/util/util_test.go
Labels: approved, lgtm, size/XXL

#1033 Improve UX experience for OperatorConfig
  api/v1alpha1/operatorconfig_types.go
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_operatorconfigs.yaml
  config/crd/bases/operator.ibm.com_operatorconfigs.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/rbac/role.yaml
Labels: approved, lgtm, size/M

#1034 Update OperatorConfig reconciliation and improve error handling
  controllers/operator/manager.go
  controllers/operatorconfig/operatorconfig_controller.go
Labels: approved, lgtm, size/M

#1035 Set channel annotation for no-op equal to spec channel when spec channel is lower
  controllers/operandrequest/reconcile_operator.go
Labels: size/XS, approved, lgtm

#1038 Bump version to 4.3.1 for 4.6.1
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  controllers/operandbindinfo/operandbindinfo_controller.go
  version/version.go
Labels: approved, lgtm, size/S

#1037 Overwrite the array in deep merge logic
  controllers/util/merge.go
Labels: size/XS, approved, lgtm

#1042 remove discontinued quay configuration
  Makefile
  common/Makefile.common.mk
  common/scripts/quay_config_docker.sh
Labels: approved, lgtm, size/M

#1040 Fix nil pointer issue when operator is not found in OperandRegistry
  controllers/operatorconfig/operatorconfig_controller.go
Labels: approved, lgtm, size/S
