Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2024-09, with the labels that each got.

#1082 Bump version to 4.3.6 for SC2 4.6.7
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#1080 Add packagemanifest CRD in test ENV
  common/Makefile.common.mk
  controllers/operandrequest/operandrequest_controller.go
  controllers/operandrequest/reconcile_operator.go
  controllers/operandrequest/reconcile_operator_test.go
  controllers/operator/manager.go
  controllers/testutil/packagemanifests_crd.yaml
Labels: approved, lgtm, size/L

#1083 Revert the host back to default value
  controllers/operandrequest/reconcile_operand.go
  controllers/util/util.go
Labels: approved, lgtm, size/L

#1084 Use PackageName name as the name of subscription
  controllers/operandrequest/operandrequest_controller.go
  controllers/operandrequest/reconcile_operator.go
Labels: size/XS, approved, lgtm

#1086 Enhance ODLM create/update logic by adding hash values
  controllers/constant/constant.go
  controllers/operandrequest/reconcile_operand.go
  controllers/util/merge.go
  controllers/util/util.go
Labels: approved, lgtm, size/L

#1085 introduce api for optional fields in resource object
  api/v1alpha1/operandconfig_types.go
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_operandconfigs.yaml
  config/crd/bases/operator.ibm.com_operandconfigs.yaml
  config/rbac/role.yaml
  controllers/operandrequest/operandrequest_controller.go
  controllers/operandrequest/reconcile_operand.go
  controllers/operandrequest/reconcile_operand_test.go
  controllers/util/util.go
  controllers/util/util_test.go
Labels: approved, lgtm, size/XL

#1087 Omit empty value in CRD
  api/v1alpha1/operandconfig_types.go
Labels: size/XS, approved, lgtm
