Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2025-02, with the labels that each got.

#1108 refactor no olm controller code to handle cleanup on operandrequest deletion
  Makefile
  api/v1alpha1/operandrequest_types.go
  controllers/operandrequestnoolm/operandrequestnoolm_controller.go
  controllers/operandrequestnoolm/reconcile_operand.go
  controllers/operandrequestnoolm/reconcile_operator.go
  controllers/operator/manager.go
Labels: approved, lgtm, size/XL

#1111 bump up version to 4.4.0 for cd release
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  helm-cluster-scoped/Chart.yaml
  helm/Chart.yaml
  helm/templates/operator-deployment.yaml
  helm/templates/rbac.yaml
  helm/values.yaml
  version/version.go
Labels: approved, lgtm, size/M

#1112 updated chart to work with CICD automation
  helm-cluster-scoped/values.yaml
  helm/templates/operator-deployment.yaml
  helm/values.yaml
Labels: approved, lgtm, size/S

#1113 updated chart to use global values to meet CPD spec
  helm-cluster-scoped/values.yaml
  helm/templates/operator-deployment.yaml
  helm/templates/rbac.yaml
  helm/values.yaml
Labels: approved, lgtm, size/M

#1117 specify operator namespace in rolebinding
  helm/templates/rbac.yaml
Labels: size/XS, approved, lgtm

#1116 Update OWNERS with my Id
  OWNERS
Labels: size/XS, approved, lgtm

#1115 Update OWNERS with my Id
  OWNERS
Labels: size/XS, approved, lgtm

#1119 Bump version to 4.3.10 for CS 4.6.11
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#1122 Add label to helm generated resources
  helm-cluster-scoped/templates/crd.yaml
  helm-cluster-scoped/values.yaml
  helm/templates/operator-deployment.yaml
  helm/templates/rbac.yaml
  helm/values.yaml
Labels: approved, lgtm, size/M

#1120 Check deployment as pre-req and return error if missing
  controllers/operator/manager.go
Labels: size/XS, approved, lgtm

#1124 replace wildcard with specific permissions
  helm/templates/rbac.yaml
Labels: approved, lgtm, size/L

#1125 Create all role and rolebindings in each namespace
  helm/templates/rbac.yaml
  helm/values.yaml
Labels: approved, lgtm, size/M

#1126 Add RH certification required metadata
  Dockerfile
  Makefile
  bundle.Dockerfile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  common/scripts/lint_go.sh
  common/scripts/next-csv.sh
  config/e2e/manager/kustomization.yaml
  config/e2e/manager/manager.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#1127 bump up odlm version to 4.5.0 for cs 4.12
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  helm-cluster-scoped/Chart.yaml
  helm/Chart.yaml
  helm/templates/operator-deployment.yaml
  helm/templates/rbac.yaml
  version/version.go
Labels: approved, lgtm, size/M

#1128 Rebase master branch onto future
  controllers/operator/manager.go
  helm-cluster-scoped/templates/crd.yaml
  helm-cluster-scoped/values.yaml
  helm/templates/operator-deployment.yaml
  helm/templates/rbac.yaml
  helm/values.yaml
Labels: approved, lgtm, size/L

#1130 add events permissions
  helm/templates/rbac.yaml
Labels: size/XS, approved, lgtm
