Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2025-05, with the labels that each got.

#1163 updated version to 4.5.1
  Makefile
  bundle.Dockerfile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  helm-cluster-scoped/Chart.yaml
  helm/Chart.yaml
  helm/templates/operator-deployment.yaml
  helm/templates/rbac.yaml
  version/version.go
Labels: approved, lgtm, size/M

#1162 Support templating system to properly handle boolean values
  controllers/operator/manager.go
  controllers/util/util.go
Labels: approved, lgtm, size/M

#1161 Use object deepcopy function with patch command for CSV update
  controllers/operatorconfig/operatorconfig_controller.go
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#1164 [CD] Support templating system to properly handle boolean values (#1162)
  controllers/operator/manager.go
  controllers/util/util.go
Labels: approved, lgtm, size/M

#1169 bump up odlm to 4.3.14 for cs 4.6.15
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#1170 [CD] Use object deepcopy function with patch command for CSV update
  controllers/operatorconfig/operatorconfig_controller.go
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#1172 [SC2] Refactor fallback channel selection to sort by semantic version and find the first available channel
  common/scripts/lint_go.sh
  controllers/operator/manager.go
Labels: approved, lgtm, size/S

#1171 Refactor fallback channel selection to sort by semantic version and find the first available channel
  common/scripts/lint_go.sh
  controllers/operator/manager.go
Labels: approved, lgtm, size/S
