Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2025-01, with the labels that each got.

#1104 Check if Object is updated except certain label and annotations
  controllers/operandrequest/operandrequest_controller.go
  controllers/operandrequest/operandrequest_controller_test.go
  controllers/operandrequest/reconcile_operand.go
  controllers/operator/manager.go
  controllers/testutil/test_util.go
Labels: approved, lgtm, size/L

#1103 add required OLM metadata
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
Labels: approved, lgtm, size/S, ok-to-test

#1107 update net to 0.33 for 4.6.10
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#1105 prototype ODLM w/o olm
  Makefile
  controllers/operandrequestnoolm/operandrequestnoolm_controller.go
  controllers/operandrequestnoolm/reconcile_operand.go
  controllers/operandrequestnoolm/reconcile_operator.go
  controllers/operator/manager.go
  controllers/util/util.go
  main.go
Labels: approved, lgtm, size/XXL

#1106 Helm chart for ODLM
  helm-cluster-scoped/Chart.yaml
  helm-cluster-scoped/templates/cluster-rbac.yaml
  helm-cluster-scoped/templates/cluster-webhook.yaml
  helm-cluster-scoped/templates/crd.yaml
  helm-cluster-scoped/values.yaml
  helm/Chart.yaml
  helm/templates/operator-deployment.yaml
  helm/templates/rbac.yaml
  helm/values.yaml
Labels: approved, size/XXL
