Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2025-03, with the labels that each got.

#1131 updated tetheredNamespace to tetheredNamespaces
  helm/templates/rbac.yaml
  helm/values.yaml
Labels: size/XS, approved, lgtm

#1132 Add Conditional Logic Support to ODLM Templating System
  controllers/operator/manager.go
  controllers/operator/manager_test.go
  controllers/util/util.go
  docs/design/operand-deployment-lifecycle-manager.md
Labels: approved, lgtm, size/XXL

#1134 Add Conditional Logic Support to ODLM Templating System (#1132)
  controllers/operator/manager.go
  controllers/operator/manager_test.go
  controllers/util/util.go
  docs/design/operand-deployment-lifecycle-manager.md
Labels: approved, lgtm, size/XXL

#1136 Array enhancement for ODLM templating system
  controllers/operator/manager.go
  controllers/operator/manager_test.go
  controllers/util/util.go
  docs/design/operand-deployment-lifecycle-manager.md
Labels: approved, lgtm, size/XL

#1137 disable irrelevant logging messages that can be misleading
  controllers/operator/manager.go
Labels: approved, lgtm, size/M

#1138 fixes and enhancements to chart
  helm-cluster-scoped/templates/cluster-rbac.yaml
  helm-cluster-scoped/templates/cluster-webhook.yaml
  helm/templates/operator-deployment.yaml
  helm/templates/rbac.yaml
  helm/values.yaml
Labels: approved, lgtm, size/M

#1139 Array enhancement for ODLM templating system (#1136)
  controllers/operator/manager.go
  controllers/operator/manager_test.go
  controllers/util/util.go
  docs/design/operand-deployment-lifecycle-manager.md
Labels: approved, lgtm, size/XL

#1140 update net pkg for security fix for sc2 4.6.12
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#1141 Add support for operator aliasing via ConfigName
  api/v1alpha1/operandconfig_types.go
  api/v1alpha1/operandregistry_types.go
  bundle/manifests/operator.ibm.com_operandregistries.yaml
  config/crd/bases/operator.ibm.com_operandregistries.yaml
  config/e2e/crd/bases/operator.ibm.com_operandregistries.yaml
  controllers/operandconfig/operandconfig_controller.go
  controllers/operandrequest/operandrequest_controller.go
  controllers/operandrequest/reconcile_operand.go
  controllers/operandrequest/reconcile_operator.go
  controllers/operator/manager.go
  test/e2e/helpers_test.go
Labels: approved, lgtm, size/M

#1142 update net pkg to 0.36.0 for 4.12 whitesource scan
  go.mod
  go.sum
Labels: approved, lgtm, size/M
