Repository IBM/operand-deployment-lifecycle-manager, pull requests merged in 2025-04, with the labels that each got.

#1143 [CD] Add support for operator aliasing via ConfigName (#1141)
  api/v1alpha1/operandconfig_types.go
  api/v1alpha1/operandregistry_types.go
  bundle/manifests/operator.ibm.com_operandregistries.yaml
  config/crd/bases/operator.ibm.com_operandregistries.yaml
  config/e2e/crd/bases/operator.ibm.com_operandregistries.yaml
  controllers/operandconfig/operandconfig_controller.go
  controllers/operandrequest/reconcile_operand.go
  controllers/operandrequest/reconcile_operator.go
  controllers/operandrequestnoolm/reconcile_operand.go
  controllers/operandrequestnoolm/reconcile_operator.go
  controllers/operator/manager.go
  helm-cluster-scoped/templates/crd.yaml
  test/e2e/helpers_test.go
Labels: approved, lgtm, size/L

#1145 Fix concurrent access issues by copying labels map in SetupWithManager
  controllers/operandbindinfo/operandbindinfo_controller.go
Labels: approved, lgtm, size/S

#1144 Refactor service status update logic to remove unnecessary context and client parameters
  api/v1alpha1/operandrequest_types.go
  controllers/operandrequest/operandrequest_controller.go
  controllers/operandrequest/reconcile_operand.go
  controllers/operandrequestnoolm/operandrequestnoolm_controller.go
  controllers/operandrequestnoolm/reconcile_operand.go
Labels: approved, lgtm, size/L

#1146 Update manager verbosity level to 2 and add debug logging for reconciliation events
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manager/manager.yaml
  controllers/operandrequest/operandrequest_controller.go
  helm/templates/operator-deployment.yaml
Labels: approved, lgtm, size/M

#1148 Separating ODLM CRD
  helm-cluster-scoped/templates/operator.ibm.com_operandbindinfos.yaml
  helm-cluster-scoped/templates/operator.ibm.com_operandconfigs.yaml
  helm-cluster-scoped/templates/operator.ibm.com_operandregistries.yaml
  helm-cluster-scoped/templates/operator.ibm.com_operandrequests.yaml
  helm-cluster-scoped/templates/operator.ibm.com_operatorconfigs.yaml
Labels: approved, lgtm, size/XXL

#1149 Refactor Bindinfo controller logic on object event watching and reconciliation triggering condition
  controllers/operandbindinfo/operandbindinfo_controller.go
Labels: approved, lgtm, size/M

#1150 bump odlm to 4.3.12 for cs 4.6.13
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#1152 [SC2] Refactor service status update logic to remove unnecessary context and client parameters
  api/v1alpha1/operandrequest_types.go
  controllers/operandrequest/operandrequest_controller.go
  controllers/operandrequest/reconcile_operand.go
Labels: approved, lgtm, size/M

#1153 [SC2] Add debug logging for reconciliation events
  controllers/operandrequest/operandrequest_controller.go
Labels: approved, lgtm, size/S

#1154 [SC2] Refactor Bindinfo controller logic on object event watching and reconciliation triggering condition
  controllers/operandbindinfo/operandbindinfo_controller.go
Labels: approved, lgtm, size/M

#1151 Fix operand deletion inconsistency in Keycloak upgrade case
  controllers/operandrequest/reconcile_operator.go
  controllers/operandrequest/reconcile_operator_test.go
Labels: approved, lgtm, size/L

#1155 [CD] Fix operand deletion inconsistency in Keycloak upgrade case
  controllers/operandrequest/reconcile_operator.go
  controllers/operandrequest/reconcile_operator_test.go
Labels: approved, lgtm, size/L

#1156 [CD] Enhance Kubernetes Resource Quantity Comparisons in Templating
  controllers/operator/manager.go
  controllers/operator/manager_test.go
  docs/design/operand-deployment-lifecycle-manager.md
Labels: approved, lgtm, size/XL

#1159 Bump ODLM to 4.3.13 for 4.6.14 release
  Makefile
  bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#1157 use Reader.Get to get resource in cluster
  controllers/operandbindinfo/operandbindinfo_controller.go
Labels: size/XS, approved, lgtm

#1158 use reader.Get to get resource in cluster
  controllers/operandbindinfo/operandbindinfo_controller.go
Labels: size/XS, approved, lgtm

#1160 4.6.14 update net and oauth pkgs for sec scans
  go.mod
  go.sum
Labels: approved, lgtm, size/M
